In [10]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
from PYTHON.lib.NR3 import NR3_function
from PYTHON.lib.network_mapper_OpenDSSnonvec import network_mapper_function as nmf2
from PYTHON.lib.network_mapper import network_mapper_function as nmf

from math import tan,acos
import copy
import pandas as pd
import time
import re
import sys

In [12]:
# fp = r"C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\NETWORKS\\"
fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/NETWORKS/'

fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'

network1 = nmf(fp, fn)

nnode = network1.nodes.nnode
nline = network1.lines.nline

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


network1.loads.aPQ = 1.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)


# network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)


print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

BASE
Vbase: 2771.2799999999997
Sbase: 1000000.0
Ibase: 360.8440864871107
Zbase: 7.679992838399998

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195313+0.00130208j 0.00065104+0

In [15]:
network1 = nmf2('compare_opendss_05node_threephase_unbalanced_oscillation_03.dss')
#network1 = network_mapper_function('compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.dss')

nnode = network1.nodes.nnode
nline = network1.lines.nline

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


network1.loads.aPQ = .750*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.15*np.ones((3,nnode))*(network1.loads.spu != 0)

network1.loads.aPQ = 1.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)

# network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)


print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

[]


IndexError: list index out of range

In [4]:
Vbase = 2771.2812921102036
Sbase = 1000000.0
Ibase = Sbase/Vbase
Zbase = Vbase/Ibase

print(Ibase)
print(Zbase)

dss.run_command('Redirect compare_opendss_05node_threephase_unbalanced_oscillation_03.dss')

# Set slack bus (sourcebus) voltage reference in p.u.
SlackBusVoltage = 1.00
dss.Vsources.PU(SlackBusVoltage)

# Solve power flow with OpenDSS file
dss.Solution.Solve()
if not dss.Solution.Converged:
    print('Initial Solution Not Converged. Check Model for Convergence')
else:
    print('Initial Model Converged. Proceeding to Next Step.')
    #Doing this solve command is required for GridPV, that is why the monitors
    #go under a reset process
    dss.Monitors.ResetAll()
    
    #set solution Params
    #setSolutionParams(dss,'daily',1,1,'off',1000000,30000)
    dss.Solution.Mode(1)
    dss.Solution.Number(1)
    dss.Solution.StepSize(1)
    dss.Solution.ControlMode(-1)
    dss.Solution.MaxControlIterations(1000000)
    dss.Solution.MaxIterations(30000)
    #Easy process to get all names and count of loads, a trick to avoid
    #some more lines of code
    TotalLoads=dss.Loads.Count()
    AllLoadNames=dss.Loads.AllNames()
    print('OpenDSS Model Compliation Done.')

print('')

# print(dss.Solution.Converged())

# Print number of buses, and bus names
print(len(dss.Circuit.AllBusNames()))
print(dss.Circuit.AllBusNames())

# Print number of loads, and load names
print(len(dss.Loads.AllNames()))
print(dss.Loads.AllNames())

print('')

VDSS = np.zeros((3,len(dss.Circuit.AllBusNames())),dtype='complex')

for k1 in range(len(dss.Circuit.AllBusNames())):
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[k1])
    print(dss.Circuit.AllBusNames()[k1])
    print(dss.Bus.Nodes())
#     print('BASE - LN')
#     print(dss.Bus.kVBase())
#     print('VMAGANGLE - LN POLAR')
#     print(dss.Bus.VMagAngle())
#     print('puVMAGANGLE - LN POLAR')
#     print(dss.Bus.puVmagAngle())
#     print('VOTLAGES - LN CARTESIAN')
#     print(dss.Bus.Voltages())
    print('puVOTLAGES - LN CARTESIAN')
    print(dss.Bus.PuVoltage())
#     print('')
    
#     print(np.asarray(dss.Bus.Nodes(),'int'))
        
#     VDSS[np.asarray(dss.Bus.Nodes(),'int'),k1] = np.array(dss.Bus.PuVoltage()[0:5:2] + 1j*dss.Bus.PuVoltage()[1:6:2])
    
    
#     VDSS[dss.Bus.Nodes()-1,k1] = dss.Bus.PuVoltage()[0:2:5]
    for k2 in range(len(dss.Bus.Nodes())):
        VDSS[int(dss.Bus.Nodes()[k2])-1,k1] = dss.Bus.PuVoltage()[2*k2] + 1j*dss.Bus.PuVoltage()[2*k2+1]
        
print('VDSS\n', np.round(VDSS,decimals=6))


# IDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

# for k1 in range(len(dss.Lines.AllNames())):
#     dss.Lines.Name(dss.Lines.AllNames()[k1])
#     print(dss.Lines.AllNames()[k1])
#     Imn = np.asarray(dss.CktElement.Currents())/Ibase
#     print(Imn)
#     print('')

STXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')
SRXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

for k1 in range(len(dss.Lines.AllNames())):
    dss.Lines.Name(dss.Lines.AllNames()[k1])
    print(dss.Lines.AllNames()[k1])
    print(dss.CktElement.BusNames())
    ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
    print(ph)
    Sk = np.asarray(dss.CktElement.Powers())/(Sbase/1000)
    print(Sk)
    
    print(Sk[0:int(len(Sk)/2)])
    print(Sk[int(len(Sk)/2):])
    
    STXtemp = Sk[0:int(len(Sk)/2)]
    SRXtemp = Sk[int(len(Sk)/2):]
    
    STXtemp = STXtemp[0:5:2] + 1j*STXtemp[1:6:2]
    print(STXtemp)
    
    SRXtemp = -(SRXtemp[0:5:2] + 1j*SRXtemp[1:6:2])
    print(SRXtemp)
    
    STXDSS[ph,k1] = STXtemp
    SRXDSS[ph,k1] = SRXtemp

print('')
print(STXDSS)
print(SRXDSS)
        

360.8439182435161
7.68


DSSException: (243, 'Redirect File: "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\compare_opendss_05node_threephase_unbalanced_oscillation_03.dss" Not Found.')

In [5]:
np.asarray(dss.CktElement.BusNames()[0].split('.')[1:])

array(['2'], dtype='<U1')

In [6]:
np.abs(VDSS - VNR)

array([[6.15138778e-06, 6.29584056e-06, 6.41191424e-06, 6.59110615e-06,
        6.58266145e-06, 6.71246771e-06, 0.00000000e+00],
       [6.26730879e-06, 6.35563656e-06, 6.41349052e-06, 6.46986807e-06,
        0.00000000e+00, 6.47776559e-06, 6.48407997e-06],
       [4.70399565e-06, 4.80590651e-06, 4.88029607e-06, 4.97685534e-06,
        5.02116720e-06, 0.00000000e+00, 0.00000000e+00]])

In [7]:
len(Sk)/2

2.0