In [4]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
from PYTHON.lib.NR3 import NR3_function
from PYTHON.lib.network_mapper_OpenDSSnonvec import network_mapper_function as nmf2
from PYTHON.lib.network_mapper import network_mapper_function as nmf

from math import tan,acos
import copy
import pandas as pd
import time
import re
import sys

In [5]:
# fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\NETWORKS\\"
fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/NETWORKS/'

fn = 'compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'

network1 = nmf(fp, fn)

nnode = network1.nodes.nnode
nline = network1.lines.nline

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


network1.loads.aPQ = .750*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.15*np.ones((3,nnode))*(network1.loads.spu != 0)


network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)


print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

BASE
Vbase: 2771.28129211
Sbase: 1000000.0
Ibase: 360.84391824354265
Zbase: 7.67999999999887

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195313+0.00130208j 0.00065104+0.0052

In [6]:
network1 = nmf2('compare_opendss_05node_threephase_unbalanced_oscillation_03.dss')
#network1 = network_mapper_function('compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.dss')

nnode = network1.nodes.nnode
nline = network1.lines.nline

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


network1.loads.aPQ = .750*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.15*np.ones((3,nnode))*(network1.loads.spu != 0)


network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)


print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]
{'sourcebus': 0, 'a01': 1, 'a02': 2, 'a03': 3, 'a04': 4, 'a05': 5, 'a06': 6}
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[1, 0, 1]
[1, 1, 0]
[0, 1, 0]
LINES
nline: 6
TXnode: ['sourcebus', 'a01', 'a02', 'a03', 'a03', 'a05']
RXnode: ['a01', 'a02', 'a03', 'a04', 'a05', 'a06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2