In [1]:
from lindist3flow import LinDist3Flow
import numpy as np

dss_path = './data/compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

LinDist3Flow = LinDist3Flow(dss_path, slackidx, Vslack)
LinDist3Flow.solve()

(array([[ 1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          0. +0.j       ],
        [-0.5-0.8660254j, -0.5-0.8660254j, -0.5-0.8660254j,
         -0.5-0.8660254j,  0. +0.j       , -0.5-0.8660254j,
         -0.5-0.8660254j],
        [-0.5+0.8660254j, -0.5+0.8660254j, -0.5+0.8660254j,
         -0.5+0.8660254j, -0.5+0.8660254j,  0. +0.j       ,
          0. +0.j       ]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[ 0.        +0.j        ,  0.        +0.j        ,
          0.1       -0.025j     ,  0.1       -0.025j     ,
          0.1       -0.025j     ,  0.1       -0.025j     ,
          0.        +0.j        ],
        [ 0.        +0.j        ,  0.        +0.j        ,
         -0.07165064-0.07410254j, -0.07165064-0.07410254j,
          0.        +0.j        , -0.07165064-0.074

In [2]:
LinDist3Flow.solve()

(array([[ 1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          0. +0.j       ],
        [-0.5-0.8660254j, -0.5-0.8660254j, -0.5-0.8660254j,
         -0.5-0.8660254j,  0. +0.j       , -0.5-0.8660254j,
         -0.5-0.8660254j],
        [-0.5+0.8660254j, -0.5+0.8660254j, -0.5+0.8660254j,
         -0.5+0.8660254j, -0.5+0.8660254j,  0. +0.j       ,
          0. +0.j       ]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 

In [1]:
import opendssdirect as dss
from lindist3flow import LinDist3Flow
import numpy as np
import time
dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/IEEE_13Node_Modified_01.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/IEEE_13Node_Modified_01.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/06node_threephase_unbalanced.dss'
dss.run_command('Redirect ' + dss_path)
nnode = len(dss.Circuit.AllBusNames())
nline = len(dss.Lines.AllNames())


# loads
# Store the loads
slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])
times = np.linspace(0, 2*np.pi, 5)

kW_list = np.array([])
kvar_list = np.array([])
for k in range(len(dss.Loads.AllNames())):
    dss.Loads.Name(dss.Loads.AllNames()[k])
    kW_list = np.append(kW_list, dss.Loads.kW())
    kvar_list = np.append(kvar_list, dss.Loads.kvar())
all_load_names = dss.Loads.AllNames()

VNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
INR01 =  np.zeros((len(times), 3, nline), dtype = "complex")
STXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
SRXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
iNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
sNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")

LinDist3Flow = LinDist3Flow(dss_path, slackidx, Vslack)
start_time = time.time()
for i in range(len(times)):
    for k,v in enumerate(all_load_names):
        LinDist3Flow.set_load_kw(v, kW_list[k]* (1 + 0.1*np.sin(2*np.pi*0.01*times[i])))
        LinDist3Flow.set_load_kvar(v, kvar_list[k] * (1 + 0.1*np.sin(2*np.pi*0.01*times[i])))
    VNR, INR, iNR, sNR, STXNR, SRXNR = LinDist3Flow.solve()
    # Time-varying load

    VNR01[i, :, :] = np.reshape(VNR, (3, nnode))
    #INR01[i, :, :] = np.reshape(INR, (3, nline))
    #STXNR01[i, :, :] = np.reshape(STXNR, (3, nline))
    #SRXNR01[i, :, :] = np.reshape(SRXNR, (3, nline))
    #iNR01[i, :, :] = np.reshape(iNR, (3, nnode))
    #sNR01[i, :, :] = np.reshape(sNR, (3, nnode))
    print(VNR)
print(time.time() - start_time)

[[ 1.        +0.j          0.99932801+0.00160646j  0.99865603+0.00321293j
   0.99737988+0.0055795j   0.99799298+0.00558766j  0.99556049+0.00709159j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.49899972-0.86684268j -0.49799943-0.86765995j
  -0.49676508-0.86892888j  0.        +0.j         -0.49698035-0.86899324j
  -0.49689536-0.86851714j]
 [-0.5       +0.8660254j  -0.50157893+0.86521028j -0.50315787+0.86439516j
  -0.50561723+0.86324779j -0.50563172+0.86192354j  0.        +0.j
   0.        +0.j        ]]
[[ 1.        +0.j          0.99932132+0.00162226j  0.99864264+0.00324452j
   0.99735381+0.00563436j  0.99797294+0.00564264j  0.99551642+0.00716123j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.49898982-0.86685074j -0.49797964-0.86767607j
  -0.49673305-0.86895753j  0.        +0.j         -0.49695043-0.8690226j
  -0.49686463-0.8685418j ]
 [-0.5       +0.8660254j  -0.50159443+0.86520212j -0.50318886+0.86437884j
  -0.50567235+0.86321995j -0.50568691+0.86188263j  0.      

IndexError: index 5 is out of bounds for axis 0 with size 5

In [ ]:
VNR01

In [1]:
import opendssdirect as dss
from lindist3flow import LinDist3Flow
import numpy as np
import time
dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/IEEE_13Node_Modified_01.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/IEEE_13Node_Modified_01.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/06node_threephase_unbalanced.dss'
dss.run_command('Redirect ' + dss_path)
nnode = len(dss.Circuit.AllBusNames())
nline = len(dss.Lines.AllNames())


# loads
# Store the loads
slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])
times = np.linspace(0, 2*np.pi, 5)

kW_list = np.array([])
kvar_list = np.array([])
for k in range(len(dss.Loads.AllNames())):
    dss.Loads.Name(dss.Loads.AllNames()[k])
    kW_list = np.append(kW_list, dss.Loads.kW())
    kvar_list = np.append(kvar_list, dss.Loads.kvar())
all_load_names = dss.Loads.AllNames()

VNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
INR01 =  np.zeros((len(times), 3, nline), dtype = "complex")
STXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
SRXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
iNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
sNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")

LinDist3Flow = LinDist3Flow(dss_path, slackidx, Vslack)
start_time = time.time()
for i in range(len(times)):
    for k,v in enumerate(all_load_names):
        LinDist3Flow.set_load_kw(v, kW_list[k]* (1 + 0.1*np.sin(2*np.pi*0.01*times[i])))
        LinDist3Flow.set_load_kvar(v, kvar_list[k] * (1 + 0.1*np.sin(2*np.pi*0.01*times[i])))
    VNR, INR, iNR, sNR, STXNR, SRXNR = LinDist3Flow.solve()
    # Time-varying load
    VNR01[i, :, :] = np.reshape(VNR, (3, nnode))
    #INR01[i, :, :] = np.reshape(INR, (3, nline))
    #STXNR01[i, :, :] = np.reshape(STXNR, (3, nline))
    #SRXNR01[i, :, :] = np.reshape(SRXNR, (3, nline))
    #iNR01[i, :, :] = np.reshape(iNR, (3, nnode))
    #sNR01[i, :, :] = np.reshape(sNR, (3, nnode))
    print(VNR)
print(time.time() - start_time)

[[ 1.        +0.j          0.99932801+0.00160646j  0.99865603+0.00321293j
   0.99737988+0.0055795j   0.99799298+0.00558766j  0.99556049+0.00709159j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.49899972-0.86684268j -0.49799943-0.86765995j
  -0.49676508-0.86892888j  0.        +0.j         -0.49698035-0.86899324j
  -0.49689536-0.86851714j]
 [-0.5       +0.8660254j  -0.50157893+0.86521028j -0.50315787+0.86439516j
  -0.50561723+0.86324779j -0.50563172+0.86192354j  0.        +0.j
   0.        +0.j        ]]
[[ 1.        +0.j          0.99932132+0.00162226j  0.99864264+0.00324452j
   0.99735381+0.00563436j  0.99797294+0.00564264j  0.99551642+0.00716123j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.49898982-0.86685074j -0.49797964-0.86767607j
  -0.49673305-0.86895753j  0.        +0.j         -0.49695043-0.8690226j
  -0.49686463-0.8685418j ]
 [-0.5       +0.8660254j  -0.50159443+0.86520212j -0.50318886+0.86437884j
  -0.50567235+0.86321995j -0.50568691+0.86188263j  0.      

In [2]:
VNR01

array([[[ 1.        +0.j        ,  0.99932801+0.00160646j,
          0.99865603+0.00321293j,  0.99737988+0.0055795j ,
          0.99799298+0.00558766j,  0.99556049+0.00709159j,
          0.        +0.j        ],
        [-0.5       -0.8660254j , -0.49899972-0.86684268j,
         -0.49799943-0.86765995j, -0.49676508-0.86892888j,
          0.        +0.j        , -0.49698035-0.86899324j,
         -0.49689536-0.86851714j],
        [-0.5       +0.8660254j , -0.50157893+0.86521028j,
         -0.50315787+0.86439516j, -0.50561723+0.86324779j,
         -0.50563172+0.86192354j,  0.        +0.j        ,
          0.        +0.j        ]],

       [[ 1.        +0.j        ,  0.99932132+0.00162226j,
          0.99864264+0.00324452j,  0.99735381+0.00563436j,
          0.99797294+0.00564264j,  0.99551642+0.00716123j,
          0.        +0.j        ],
        [-0.5       -0.8660254j , -0.49898982-0.86685074j,
         -0.49797964-0.86767607j, -0.49673305-0.86895753j,
          0.        +0.j        