In [1]:
from lindist3flow import LinDist3Flow
import numpy as np

dss_path = './data/compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

LinDist3Flow = LinDist3Flow(dss_path, slackidx, Vslack)
LinDist3Flow.solve()

(array([[ 1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          0. +0.j       ],
        [-0.5-0.8660254j, -0.5-0.8660254j, -0.5-0.8660254j,
         -0.5-0.8660254j,  0. +0.j       , -0.5-0.8660254j,
         -0.5-0.8660254j],
        [-0.5+0.8660254j, -0.5+0.8660254j, -0.5+0.8660254j,
         -0.5+0.8660254j, -0.5+0.8660254j,  0. +0.j       ,
          0. +0.j       ]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[ 0.        +0.j        ,  0.        +0.j        ,
          0.1       -0.025j     ,  0.1       -0.025j     ,
          0.1       -0.025j     ,  0.1       -0.025j     ,
          0.        +0.j        ],
        [ 0.        +0.j        ,  0.        +0.j        ,
         -0.07165064-0.07410254j, -0.07165064-0.07410254j,
          0.        +0.j        , -0.07165064-0.074

In [2]:
LinDist3Flow.solve()

(array([[ 1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          1. +0.j       ,  1. +0.j       ,  1. +0.j       ,
          0. +0.j       ],
        [-0.5-0.8660254j, -0.5-0.8660254j, -0.5-0.8660254j,
         -0.5-0.8660254j,  0. +0.j       , -0.5-0.8660254j,
         -0.5-0.8660254j],
        [-0.5+0.8660254j, -0.5+0.8660254j, -0.5+0.8660254j,
         -0.5+0.8660254j, -0.5+0.8660254j,  0. +0.j       ,
          0. +0.j       ]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]]),
 array([[0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 

In [1]:
import opendssdirect as dss
from lindist3flow import LinDist3Flow
import numpy as np
import time
dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/IEEE_13Node_Modified_01.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/IEEE_13Node_Modified_01.dss'
#dss_path = '/home/toanngo/Documents/GitHub/LinDist3Flow/lindist3flow/data/06node_threephase_unbalanced.dss'
dss.run_command('Redirect ' + dss_path)
nnode = len(dss.Circuit.AllBusNames())
nline = len(dss.Lines.AllNames())


# loads
# Store the loads
slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])
times = np.linspace(0, 2*np.pi, 5)

kW_list = np.array([])
kvar_list = np.array([])
for k in range(len(dss.Loads.AllNames())):
    dss.Loads.Name(dss.Loads.AllNames()[k])
    kW_list = np.append(kW_list, dss.Loads.kW())
    kvar_list = np.append(kvar_list, dss.Loads.kvar())
all_load_names = dss.Loads.AllNames()

VNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
INR01 =  np.zeros((len(times), 3, nline), dtype = "complex")
STXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
SRXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
iNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
sNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")

LinDist3Flow = LinDist3Flow(dss_path, slackidx, Vslack)
start_time = time.time()
for i in range(len(times)):

    VNR, INR, iNR, sNR, STXNR, SRXNR = LinDist3Flow.solve()
    # Time-varying load
    for k,v in enumerate(all_load_names):
        LinDist3Flow.set_load_kw(v, kW_list[k]* (1 + 0.1*np.sin(2*np.pi*0.01*times[i])))
        LinDist3Flow.set_load_kvar(v, kvar_list[k] * (1 + 0.1*np.sin(2*np.pi*0.01*times[i])))
    #VNR01[i, :, :] = np.reshape(VNR, (3, nnode))
    #INR01[i, :, :] = np.reshape(INR, (3, nline))
    #STXNR01[i, :, :] = np.reshape(STXNR, (3, nline))
    #SRXNR01[i, :, :] = np.reshape(SRXNR, (3, nline))
    #iNR01[i, :, :] = np.reshape(iNR, (3, nnode))
    #sNR01[i, :, :] = np.reshape(sNR, (3, nnode))
    print(VNR)
print(time.time() - start_time)

[[ 1.        +0.j          0.99881434+0.00285394j  0.99762869+0.00570789j
   0.99539355+0.00972331j  0.99662511+0.0097544j   0.99206618+0.01201538j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.498296  -0.86838677j -0.49659199-0.87074814j
  -0.49471926-0.87474368j  0.        +0.j         -0.49576335-0.87635006j
  -0.49556479-0.87586776j]
 [-0.5       +0.8660254j  -0.5030413 +0.86355281j -0.50608259+0.86108022j
  -0.51077419+0.85710962j -0.51078774+0.85445899j  0.        +0.j
   0.        +0.j        ]]
[[ 1.        +0.j          0.99881434+0.00285394j  0.99762869+0.00570789j
   0.99539355+0.00972331j  0.99662511+0.0097544j   0.99206618+0.01201538j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.498296  -0.86838677j -0.49659199-0.87074814j
  -0.49471926-0.87474368j  0.        +0.j         -0.49576335-0.87635006j
  -0.49556479-0.87586776j]
 [-0.5       +0.8660254j  -0.5030413 +0.86355281j -0.50608259+0.86108022j
  -0.51077419+0.85710962j -0.51078774+0.85445899j  0.     

In [2]:
VNR01

array([[[ 1.        +0.j        ,  0.99881434+0.00285394j,
          0.99762869+0.00570789j,  0.99539355+0.00972331j,
          0.99662511+0.0097544j ,  0.99206618+0.01201538j,
          0.        +0.j        ],
        [-0.5       -0.8660254j , -0.498296  -0.86838677j,
         -0.49659199-0.87074814j, -0.49471926-0.87474368j,
          0.        +0.j        , -0.49576335-0.87635006j,
         -0.49556479-0.87586776j],
        [-0.5       +0.8660254j , -0.5030413 +0.86355281j,
         -0.50608259+0.86108022j, -0.51077419+0.85710962j,
         -0.51078774+0.85445899j,  0.        +0.j        ,
          0.        +0.j        ]],

       [[ 1.        +0.j        ,  0.99881434+0.00285394j,
          0.99762869+0.00570789j,  0.99539355+0.00972331j,
          0.99662511+0.0097544j ,  0.99206618+0.01201538j,
          0.        +0.j        ],
        [-0.5       -0.8660254j , -0.498296  -0.86838677j,
         -0.49659199-0.87074814j, -0.49471926-0.87474368j,
          0.        +0.j        