In [1]:
import opendssdirect as dss
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import random 

In [6]:
print('delta \n ')
fn = "02node_delta_mike.dss"
dss.run_command('Redirect 02node_delta_mike.dss')
for n in range(len(dss.Circuit.AllBusNames())):
    print(dss.Circuit.AllBusNames()[n])
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[n])
    print(dss.Bus.kVBase())
    print(dss.Bus.PuVoltage())
    print(dss.Bus.puVmagAngle())
    
print('\nwye \n')
fn = "02node_wye_mike.dss"
dss.run_command('Redirect ' + fn)
for n in range(len(dss.Circuit.AllBusNames())):
    print(dss.Circuit.AllBusNames()[n])
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[n])
    print(dss.Bus.kVBase())
    print(dss.Bus.PuVoltage())
    print(dss.Bus.puVmagAngle())
    
    # Zbase = dss.Bus.kVBase() * 1000
    

delta 
 
sourcebus
2.7712812921102037
[0.9999994085905026, -3.81180177224462e-06, -0.49999940790218744, -0.8660215938627811, -0.5000000001794338, 0.8660254038235828]
[0.9999994085977676, -0.00021840028304129884, 0.9999964044631209, -120.00007976040173, 1.000000000123617, 120.00000000133831]
a01
2.7712812921102037
[0.9978768825072274, 0.004843010660665105, -0.49787616529222994, -0.870873389660258]
[0.9978886347657249, 0.27807227243327626, 1.0031456209267144, -119.75649683205616]
a02
2.7712812921102037
[0.9893917684861911, 0.024242432181195286, -0.48938977745640894, -0.8902816527083909]
[0.9896887223093395, 1.4036009054067546, 1.0159250835706428, -118.79769186103735]

wye 

sourcebus
2.7712812921102037
[0.9999989978512737, -1.2800592122138386e-06, -0.5000004682550839, -0.8660238129911836, -0.49999991583704195, 0.8660254270930919]
[0.999998997852093, -7.334206388236425e-05, 0.9999988564608919, -120.00006880113497, 0.9999999781044104, 119.99999514968005]
a01
2.7712812921102037
[0.997394004

In [7]:
Vbase = 2.77128e3
Sbase = 1e6
Ibase = Sbase/Vbase
Zbase = Vbase/Ibase

print(Ibase)

Vdelta = np.zeros((2,3),dtype='complex')
Idelta = np.zeros((2,2),dtype='complex')
Sdelta = np.zeros((2,2),dtype='complex')

print('delta \n ')
dss.run_command('Redirect 02node_delta_mike.dss')
dss.Solution.Solve()

for n in range(len(dss.Circuit.AllBusNames())):
    print(dss.Circuit.AllBusNames()[n])
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[n])
    print(dss.Bus.kVBase())
    print(dss.Bus.PuVoltage())
    print(dss.Bus.puVmagAngle())

    Vk = np.asarray(dss.Bus.PuVoltage())
    Vk = Vk[0::2] + 1j*Vk[1::2]
    Vk = Vk[0:2]
    Vdelta[:,n] = Vk
    print('')

for n in range(len(dss.Lines.AllNames())):
    print(dss.Lines.AllNames()[n])
    dss.Lines.Name(dss.Lines.AllNames()[n])
    print(dss.CktElement.Currents())
    Ik = np.asarray(dss.CktElement.Currents())
    Ik = (Ik[0::2] + 1j*Ik[1::2])/Ibase
    Ik = -Ik[2:]

    Idelta[:,n] = Ik
    print(Ik)

    print(dss.CktElement.Powers())
    Sk = np.asarray(dss.CktElement.Powers())
    Sk = 1e3*(Sk[0::2] + 1j*Sk[1::2])/Sbase
    Sk = -Sk[2:]

    Sdelta[:,n] = Sk
    print(Sk)

    print('')

    print('Vdelta \n' + str(Vdelta))
    print('Idelta \n' + str(Idelta))
    print('Sdelta \n' + str(Sdelta))

360.84408648711064
delta 
 
sourcebus
2.7712812921102037
[0.9999994085905742, -3.81180081320667e-06, -0.49999940790225883, -0.8660215938637402, -0.5000000001794338, 0.8660254038235828]
[0.9999994085978391, -0.0002184002280924238, 0.9999964044639873, -120.00007976037779, 1.000000000123617, 120.00000000133831]

a01
2.7712812921102037
[0.9978768831313111, 0.004843009498434852, -0.4978761659163147, -0.8708733884980279]
[0.9978886353841605, 0.27807220552837186, 1.0031456202274756, -119.75649689594775]

a02
2.7712812921102037
[0.9893917716063354, 0.02424242636619804, -0.4893897805765534, -0.8902816468933935]
[0.989688725286109, 1.4036005644370921, 1.0159250799778397, -118.797692173224]

line_sub_a01
[92.42003094797292, 8.4420803688472, -92.37026765981886, -8.413349720553924, -92.42278826565234, -8.425905628546388, 92.38297757162172, 8.402921100761887]
[ 0.25612942+0.02335054j -0.2560191 -0.02328685j]
[256.12166213092974, -23.396341842106466, 148.18379628702684, 210.02980156777755, -255.69883

In [8]:
Vbase = 2.77128e3
Sbase = 1e6
Ibase = Sbase/Vbase
Zbase = Vbase/Ibase

print(Ibase)

Vwye = np.zeros((2,3),dtype='complex')
Iwye = np.zeros((2,2),dtype='complex')
Swye = np.zeros((2,2),dtype='complex')

print('wye \n ')
dss.run_command('Redirect 02node_wye_mike.dss')
dss.Solution.Solve()

for n in range(len(dss.Circuit.AllBusNames())):
    print(dss.Circuit.AllBusNames()[n])
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[n])
    print(dss.Bus.kVBase())
    print(dss.Bus.PuVoltage())
    print(dss.Bus.puVmagAngle())

    Vk = np.asarray(dss.Bus.PuVoltage())
    Vk = Vk[0::2] + 1j*Vk[1::2]
    Vk = Vk[0:2]
    Vwye[:,n] = Vk
    print('')

for n in range(len(dss.Lines.AllNames())):
    print(dss.Lines.AllNames()[n])
    dss.Lines.Name(dss.Lines.AllNames()[n])
    print(dss.CktElement.Currents())
    Ik = np.asarray(dss.CktElement.Currents())
    Ik = (Ik[0::2] + 1j*Ik[1::2])/Ibase
    Ik = -Ik[2:]

    Iwye[:,n] = Ik
    print(Ik)

    print(dss.CktElement.Powers())
    Sk = np.asarray(dss.CktElement.Powers())
    Sk = 1e3*(Sk[0::2] + 1j*Sk[1::2])/Sbase
    Sk = -Sk[2:]

    Swye[:,n] = Sk
    print(Sk)

    print('')

    print(Vwye)
    print(Iwye)
    print(Swye)

360.84408648711064
wye 
 
sourcebus
2.7712812921102037
[0.9999989978603196, -1.2800453761090929e-06, -0.5000004682471609, -0.8660238130170836, -0.49999991583824144, 0.8660254270932601]
[0.9999989978611389, -7.334127113049955e-05, 0.9999988564793606, -120.00006879999987, 0.999999978105156, 119.99999514973474]

a01
2.7712812921102037
[0.9973940392864709, 0.0024225721356642043, -0.5011082491207173, -0.8673186315470257]
[0.9973969813769915, 0.13916554591903244, 1.0016741416076569, -120.01791263789364]

a02
2.7712812921102037
[0.9869792349961214, 0.012130074632262199, -0.5055459611022364, -0.8724989747918934]
[0.987053772103685, 0.7041354747242142, 1.0083804737298758, -120.08898849008754]

line_sub_a01
[36.76548131037271, -17.74765879141978, -33.35792463705695, -22.044617494192607, -36.76821537806791, 17.7638350642992, 33.37060477914781, 22.03416598696731]
[ 0.10189502-0.04922856j -0.09247929-0.06106284j]
[101.8874514028039, 49.18357507781336, 99.12912433504349, 49.512925438963684, -101.510

In [9]:
Vdelta - Vwye
np.linalg.norm(Vdelta - Vwye)

0.027549034834709944

In [10]:
Idelta - Iwye
np.linalg.norm(Idelta - Iwye)

0.33831578704084714

In [11]:
Sdelta - Swye

array([[0.15418857-0.07140769j, 0.15400682-0.06671648j],
       [0.04844265+0.16175641j, 0.04599318+0.16671648j]])

In [12]:
Ngen = 20

Npop = 100

Nbest = 10

PQpop = 500*np.random.randn(4,Npop)

Vwye = np.zeros((2,3,Npop),dtype='complex')
Iwye = np.zeros((2,2,Npop),dtype='complex')
Swye = np.zeros((2,2,Npop),dtype='complex')

Jmin = np.zeros(Ngen)
Jmean = np.zeros(Ngen)
Jstd = np.zeros(Ngen)

for kgen in range(0,Ngen):

    Jgen = np.zeros(Npop)


    for kpop in range(0,Npop):


        dss.Loads.Name('load_A02_a_01')
        dss.Loads.kW(PQpop[0,kpop])
        dss.Loads.kvar(PQpop[1,kpop])

        dss.Loads.Name('load_A02_b_01')
        dss.Loads.kW(PQpop[2,kpop])
        dss.Loads.kvar(PQpop[3,kpop])

        dss.Solution.Solve()

        for kbus in range(len(dss.Circuit.AllBusNames())):
            # print(dss.Circuit.AllBusNames()[kbus])
            dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[kbus])
            # print(dss.Bus.kVBase())
            # print(dss.Bus.PuVoltage())
            # print(dss.Bus.puVmagAngle())

            Vk = np.asarray(dss.Bus.PuVoltage())
            Vk = Vk[0::2] + 1j*Vk[1::2]
            Vk = Vk[0:2]
            Vwye[:,kbus,kpop] = Vk

        for kline in range(len(dss.Lines.AllNames())):
            # print(dss.Lines.AllNames()[n])
            dss.Lines.Name(dss.Lines.AllNames()[kline])
            # print(dss.CktElement.Currents())
            Ik = np.asarray(dss.CktElement.Currents())
            Ik = (Ik[0::2] + 1j*Ik[1::2])/Ibase
            Ik = -Ik[2:]

            Iwye[:,kline,kpop] = Ik
            # print(Ik)

            # print(dss.CktElement.Powers())
            Sk = np.asarray(dss.CktElement.Powers())
            Sk = 1e3*(Sk[0::2] + 1j*Sk[1::2])/Sbase
            Sk = -Sk[2:]

            Swye[:,kline,kpop] = Sk
            # print(Sk)

            Jgen[kpop] = np.linalg.norm(Vdelta - Vwye[:,:,kpop])**2 + np.linalg.norm(Idelta - Iwye[:,:,kpop])**2

    # Sort SFCs by cost, select the Nbest best
    # print(Jgen)
    idxNbest = Jgen.argsort()[:Nbest]
    # print(idxNbest)

    # Select the nbest best NNs, eliminate rest    
    PQpop = PQpop[:,idxNbest]

    for k1 in range(Nbest):
        for k2 in range(Nbest):
            if k1 != k2:

                # random mutation parameters
                mu = 0
                sigma = 200
                
                # Create new SFC for 10% of cases
                if np.random.rand() <= 0.2:

                    mu = 0
                    sigma = 100
                                        
                    PQpoptemp = np.random.normal(0,100,(4,1))
                    PQpop = np.concatenate((PQpop,PQpoptemp), axis=1)
                
                # Reproduce NNs for 90% of cases
                else:

                    mu = 0
                    sigma = 1

                    # reproduce NNs and add random mutation
                    gamma = np.random.rand(4,1)
                    PQpoptemp = gamma*PQpop[:,k1] + (1 - gamma)*PQpop[:,k2]
                    PQpoptemp += np.random.normal(mu,sigma,(4,1))
                    PQpop = np.concatenate((PQpop,PQpoptemp), axis=1)
    
    # Store cost function values for current generation
    Jmin[kgen] = np.min(Jgen)
    Jmean[kgen] = np.mean(Jgen)
    Jstd[kgen] = np.std(Jgen)
        

    print(kgen)

    #     print(kgen, np.min(JJ), np.mean(JJ), np.std(JJ))
    print('{0:2d}  {1:3.4f}  {2:3.4f}  {3:3.4f}'.format(kgen, np.min(Jgen), np.mean(Jgen), np.std(Jgen)))
#     print('{0:2d}  {1:3.4f}'.format(kgen, np.min(Jgen)))
    print('Best PQ for generation')
    print(PQpop[:,idxNbest[0]])
    print('')

print('PQ')
print(PQpop[:,idxNbest[0]])

print('Vwye')
print(Vwye[:,:,idxNbest[0]])
print('Iwye')
print(Iwye[:,:,idxNbest[0]])
print('Swye')
print(Swye[:,:,idxNbest[0]])



0
 0  0.0537  2.0030  1.2475
Best PQ for generation
[ 447.097293   -338.54290311  209.79793095  212.52170195]

1
 1  0.0367  0.3443  0.2897
Best PQ for generation
[184.36928411 265.68535959 158.03686076 294.17661968]

2
 2  0.0367  0.1419  0.0809
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

3
 3  0.0367  0.1367  0.0762
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

4
 4  0.0367  0.1534  0.1035
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

5
 5  0.0367  0.1554  0.0966
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

6
 6  0.0367  0.1525  0.0963
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

7
 7  0.0367  0.1448  0.0781
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

8
 8  0.0367  0.1499  0.0920
Best PQ for generation
[311.12462552  -5.71108718  47.08994484 147.31731328]

9
 9  0.0367  0.1537  0.0942
Best

In [14]:
print('Vdelta \n' + str(Vdelta))
print('Idelta \n' + str(Idelta))
print('Sdelta \n' + str(Sdelta))

Vdelta 
[[ 0.99999941-3.81180081e-06j  0.99787688+4.84300950e-03j
   0.98939177+2.42424264e-02j]
 [-0.49999941-8.66021594e-01j -0.49787617-8.70873388e-01j
  -0.48938978-8.90281647e-01j]]
Idelta 
[[ 0.25612942+0.02335054j  0.25616238+0.02317229j]
 [-0.2560191 -0.02328685j -0.25616238-0.02317229j]]
Sdelta 
[[0.25569884-0.02206054j 0.25400682-0.01671648j]
 [0.14774577+0.21136635j 0.14599318+0.21671648j]]
