In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.NR3 import NR3_function


In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'

In [3]:
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu

BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [4]:
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)

'''
VNR = np.round(VNR,decimals=6)
INR = np.round(INR,decimals=6)
STXNR = np.round(STXNR,decimals=6)
SRXNR = np.round(SRXNR,decimals=6)
iNR = np.round(iNR,decimals=6)
sNR = np.round(sNR,decimals=6)
'''

print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

6
(36, 1)
(36, 1)
ftsubv
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ftkvl
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
ftkcl
[[ 0.       ]
 [ 0.       ]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.025    ]
 [ 1.       ]
 [ 0.       ]
 [ 0.       ]
 [ 0.       ]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.025    ]
 [-0.5      ]
 [-0.8660254]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.05     ]
 [ 0.       ]
 [ 0.       ]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.025    ]
 [-0.1      ]
 [-0.025    ]
 [-0.5      ]
 [ 0.8660254]
 [-0.5      ]
 [ 0.8660254]]
jsubv
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

[[ 0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   1.         0.        -1.        -0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.

6
(36, 1)
(36, 1)
ftsubv
[[ 0.00000000e+00]
 [-5.37788578e-19]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
ftkvl
[[ 4.11996826e-18]
 [ 1.35525272e-18]
 [ 4.77048956e-18]
 [ 5.42101086e-19]
 [-4.20670443e-17]
 [-8.67361738e-19]
 [ 5.03069808e-17]
 [ 1.68051337e-18]
 [ 8.08814821e-17]
 [ 1.51788304e-18]
 [ 3.10847333e-16]
 [-1.94206587e-17]
 [ 1.30104261e-18]
 [-5.07948718e-17]
 [ 1.95156391e-18]
 [ 6.06069014e-17]
 [-1.51788304e-17]
 [-3.20923843e-17]
 [-3.93662581e-18]
 [-2.90345448e-18]
 [ 2.38524478e-17]
 [-2.47198095e-17]
 [-2.72676846e-17]
 [ 3.21736995e-17]
 [ 4.50486003e-17]
 [-3.71745820e-17]
 [-6.55400213e-17]
 [ 7.41865337e-17]
 [-4.22838847e-18]
 [-3.31223764e-17]
 [-1.66425033e-17]
 [ 2.44623115e-17]
 [ 2.02453255e-17]
 [-8.04389212e-17]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
ftkcl
[[ 1.23355102e-16]
 [ 3.22008045e-17]
 [-2.02834926e-04]
 [ 3.13558976e-04]
 [-3.78000580e-04]
 [ 5.44110140e-04]
 [-3.16738003e-04]
 [ 5.59798265e-04]
 [-5.867595

6
(36, 1)
(36, 1)
ftsubv
[[0.00000000e+00]
 [1.61529786e-19]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
ftkvl
[[ 1.92987987e-17]
 [-7.04731412e-19]
 [ 1.95156391e-17]
 [ 1.62630326e-19]
 [-8.41340886e-17]
 [ 1.08420217e-19]
 [ 2.71050543e-17]
 [ 1.62630326e-19]
 [ 8.13151629e-17]
 [ 2.16840434e-19]
 [ 9.55488205e-20]
 [ 9.45576793e-19]
 [ 6.72205347e-18]
 [-3.97902197e-17]
 [ 6.50521303e-18]
 [ 7.09610322e-17]
 [-3.03576608e-17]
 [ 1.00830802e-17]
 [ 6.37024978e-19]
 [ 7.63210817e-19]
 [ 1.65340831e-17]
 [ 3.63207728e-18]
 [ 1.56938264e-17]
 [-4.40728183e-17]
 [ 7.48099499e-18]
 [ 3.36102673e-18]
 [ 7.31836466e-18]
 [ 3.26615904e-18]
 [ 3.79470760e-17]
 [-2.00848452e-17]
 [-4.88433079e-17]
 [-2.05862888e-17]
 [ 2.00604386e-18]
 [ 4.81370022e-19]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
ftkcl
[[-6.91178885e-17]
 [ 6.07153217e-18]
 [-5.66572140e-09]
 [ 3.46881246e-09]
 [-1.92300518e-08]
 [ 1.03001095e-08]
 [-1.55394209e-08]
 [ 1.31097417e-08]
 [-3.91922919e-08

6
(36, 1)
(36, 1)
ftsubv
[[0.00000000e+00]
 [5.21051251e-24]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
ftkvl
[[-1.86482774e-17]
 [ 5.42101086e-20]
 [-1.86482774e-17]
 [ 5.42101086e-20]
 [ 4.42354486e-17]
 [ 1.08420217e-19]
 [-3.25260652e-17]
 [-5.42101086e-19]
 [-2.47198095e-17]
 [-2.16840434e-19]
 [ 3.32095681e-24]
 [ 8.78666799e-24]
 [ 1.60461922e-17]
 [-3.76218154e-17]
 [-3.94649591e-17]
 [ 7.34004871e-17]
 [ 3.77302356e-17]
 [-7.04731412e-18]
 [-1.37534526e-23]
 [ 7.22803945e-24]
 [ 1.37151575e-17]
 [-5.75711354e-17]
 [-2.83247818e-17]
 [-1.52330405e-17]
 [-2.68882139e-17]
 [-1.62359275e-17]
 [-2.68882139e-17]
 [-1.62359275e-17]
 [ 8.67361738e-19]
 [ 4.68104288e-17]
 [ 6.27753058e-17]
 [-5.35324823e-17]
 [-1.06063622e-22]
 [-1.28044215e-23]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
ftkcl
[[-1.31730564e-17]
 [-1.84314369e-17]
 [ 7.26415456e-18]
 [ 1.90819582e-17]
 [-2.77284706e-17]
 [ 1.46367293e-17]
 [ 0.00000000e+00]
 [ 1.38777878e-17]
 [-1.38777912e-17

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.38777878e-17
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  9.99406355e-01  1.71036824e-03
  -9.99406355e-01 -1.71036824e-03  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000