In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.NR3 import NR3_function


In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\NETWORKS\\"
fn = 'compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'

In [3]:
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = .750*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.15*np.ones((3,nnode1))*(network1.loads.spu != 0)


network1.loads.spu = 1.25*network1.loads.spu

BASE
Vbase: 2771.2799999999997
Sbase: 1000000.0
Ibase: 360.8440864871107
Zbase: 7.679992838399998

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195313+0.00130208j 0.00065104+0

In [4]:
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)

'''
VNR = np.round(VNR,decimals=6)
INR = np.round(INR,decimals=6)
STXNR = np.round(STXNR,decimals=6)
SRXNR = np.round(SRXNR,decimals=6)
iNR = np.round(iNR,decimals=6)
sNR = np.round(sNR,decimals=6)
'''

print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

0.0
0.0
0.0
0.0
0.0
0.0
0.0


0.03125
0.75
0.1
0.0
0.15
0.0
0.0


0.03125
0.75
0.1
0.0
0.15
0.0
0.0


0.03125
0.75
0.1
0.0
0.15
0.0
0.0


0.03125
0.75
0.1
0.0
0.15
0.0
0.0


0.0
0.0
0.0
-1.4874168143337463e-17
0.0
-2.9748336286674926e-17
6.162975822039155e-32


0.03125
0.75
0.1
-1.4874168143337463e-17
0.15
-2.9748336286674926e-17
6.162975822039155e-32


0.03125
0.75
0.1
-1.4874168143337463e-17
0.15
-2.9748336286674926e-17
6.162975822039155e-32


0.03125
0.75
0.1
-1.4874168143337463e-17
0.15
-2.9748336286674926e-17
6.162975822039155e-32


0.03125
0.75
0.1
-1.4874168143337463e-17
0.15
-2.9748336286674926e-17
6.162975822039155e-32


0.0
0.0
0.0
-1.4874168143337463e-17
0.0
-2.9748336286674926e-17
6.162975822039155e-32


0.03125
0.75
0.1
-1.4874168143337463e-17
0.15
-2.9748336286674926e-17
6.162975822039155e-32


0.0
0.0
0.0
-1.4874168143337463e-17
0.0
-2.9748336286674926e-17
6.162975822039155e-32


0.03125
0.75
0.1
-1.4874168143337463e-17
0.15
-2.9748336286674926e-17
6.162975822039155e-32


In [5]:
network1.loads.aPQ

array([[0.  , 0.  , 0.75, 0.75, 0.75, 0.75, 0.  ],
       [0.  , 0.  , 0.75, 0.75, 0.  , 0.75, 0.75],
       [0.  , 0.  , 0.75, 0.  , 0.75, 0.  , 0.  ]])