In [1]:
# cd.. In separate cell if used

from lib.network_mapper import network_mapper_function
from lib.NR3 import NR3_function
#from lib.computeFTreal import computeFTrealfunction
#from lib.computeJTreal import computeJTrealfunction
#from lib import *
import numpy as np
import math
import matplotlib.pyplot as plt
#matplotlib inline
fig_size = np.array([18, 6])
plt.rcParams["figure.figsize"] = fig_size

# z = exp(s*T)

# zoh
# z ~ 1 + s*T
# s ~ (z - 1)/T

# bilinear transform
# z ~ (2 + sT)/(2 - sT)
# s ~ (2/T)(z - 1)/(z + 1)

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\NETWORKS\\"
fn = 'ieee_13node_mesh_closed.txt'
fn = "ieee_34node.txt"
#fn = "03node_fullphase_radial_example.txt"
fn = "05node_singlephase_radial.txt" #this one is a problem #same PH problem
#fn = '05node_singlephase_mesh.txt' #this one is the same problem 
# fn = 'ieee_13node_balance.txt'
#fn = '05node_fullphase_radial.txt' #PH != SNXNR and SRXNR


#fn = '03node_fullphase_mesh_example.txt'
#fn = '03node_singlephase_mesh_example.txt' #same problem
##fn = '03node_singlephase_radial_example.txt' #same problem
#fn = 'ieee_13node_mesh_open.txt'
#fn = '03node_fullphase_radial_COPY.txt'

#fn = '03node_fullphase_radial_example.txt' #PH problem
#fn = 'ieee_34node - Copy.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1.00*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode1))*(network1.loads.spu != 0)

network1.loads.spu = 2.0*network1.loads.spu

# Capacitor parameters

#network1.caps.cappu = 1*network1.caps.cappu

# Controller parameters

#network1.cons.wmaxpu = 0.5*network1.cons.wmaxpu


BASE
Vbase: 5000.0
Sbase: 5000000.0
Ibase: 1000.0
Zbase: 5.0

NODES
nnode: 6
nodelist: ['A0', 'A1', 'A2', 'A3', 'A4', 'A5']
phases: ['a', 'a', 'a', 'a', 'a', 'a']
PH:
 [[1 1 1 1 1 1]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

LINES
nline: 5
TXnode: ['A0', 'A1', 'A2', 'A2', 'A4']
RXnode: ['A1', 'A2', 'A3', 'A4', 'A5']
TXnum: [0 1 2 2 4]
RXnum: [1 2 3 4 5]
phases: ['a', 'a', 'a', 'a', 'a']
PH:
 [[1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
config: ['12', '12', '12', '12', '12']
length: [ 76.2 304.8 228.6 228.6 228.6]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4]]
innodes:
 [[-1  0  1  2  2  4]]
outlines:
 [[ 0  1  2 -1  4 -1]
 [-1 -1  3 -1 -1 -1]]
outnodes:
 [[ 1  2  3 -1  5 -1]
 [-1 -1  4 -1 -1 -1]]

CONFIGS
nconf: 3
conflist: ['12', '13', '14']
12 - FZpl:
 [[4.30611306e-05+1.26499062e-04j 1.93868294e-05+6.23485404e-05j
  1.96353785e-05+5.26426982e-05j]
 [1.93868294e-05+6.23485404e-05j 4.19426597e-05+1.30214871e-04j
  1.90761430e-05+4.78332733e-05j]
 [1.96353785e-05+5.26426982e-05j 1.90761430e-05+4.7833

In [3]:
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)

'''
VNR = np.round(VNR,decimals=6)
INR = np.round(INR,decimals=6)
STXNR = np.round(STXNR,decimals=6)
SRXNR = np.round(SRXNR,decimals=6)
iNR = np.round(iNR,decimals=6)
sNR = np.round(sNR,decimals=6)
'''

print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

VNR
 [[1.      +0.j       0.992024-0.004332j 0.960118-0.021658j
  0.951872-0.025445j 0.951398-0.026639j 0.948835-0.029801j]
 [0.      +0.j       0.      +0.j       0.      +0.j
  0.      +0.j       0.      +0.j       0.      +0.j      ]
 [0.      +0.j       0.      +0.j       0.      +0.j
  0.      +0.j       0.      +0.j       0.      +0.j      ]]
INR
 [[0.655144-0.604487j 0.655144-0.604487j 0.20435 -0.215575j
  0.24635 -0.217654j 0.125023-0.046084j]
 [0.      +0.j       0.      +0.j       0.      +0.j
  0.      +0.j       0.      +0.j      ]
 [0.      +0.j       0.      +0.j       0.      +0.j
  0.      +0.j       0.      +0.j      ]]
STXNR
 [[0.655144+0.604487j 0.652536+0.596828j 0.200869+0.202551j
  0.241239+0.203638j 0.120175+0.040513j]
 [0.      +0.j       0.      +0.j       0.      +0.j
  0.      +0.j       0.      +0.j      ]
 [0.      +0.j       0.      +0.j       0.      +0.j
  0.      +0.j       0.      +0.j      ]]
SRXNR
 [[0.652536+0.596828j 0.642107+0.56619j  0.2     +0.2

In [4]:
fid = open('NR3-' + fn[:-4] + '-python.txt','w')

phstr = ['a','b','c']

fid.write('VNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nnode):
        wstr = '{0:.6f}'.format(VNR[ph,k1].real) + ' ' + '{0:.6f}'.format(VNR[ph,k1].imag) + '\n'
        fid.write(wstr)

fid.write('\n\nINR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nline):
        wstr = '{0:.6f}'.format(INR[ph,k1].real) + ' ' + '{0:.6f}'.format(INR[ph,k1].imag) + '\n'
        fid.write(wstr)
        
fid.write('\n\nSTXNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nline):
        wstr = '{0:.6f}'.format(STXNR[ph,k1].real) + ' ' + '{0:.6f}'.format(STXNR[ph,k1].imag) + '\n'
        fid.write(wstr)

fid.write('\n\nSRXNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nline):
        wstr = '{0:.6f}'.format(SRXNR[ph,k1].real) + ' ' + '{0:.6f}'.format(SRXNR[ph,k1].imag) + '\n'
        fid.write(wstr)
        
fid.write('\n\niNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nnode):
        wstr = '{0:.6f}'.format(iNR[ph,k1].real) + ' ' + '{0:.6f}'.format(iNR[ph,k1].imag) + '\n'
        fid.write(wstr)
        
fid.write('\n\nsNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nnode):
        wstr = '{0:.6f}'.format(sNR[ph,k1].real) + ' ' + '{0:.6f}'.format(sNR[ph,k1].imag) + '\n'
        fid.write(wstr)

fid.close()