In [1]:
# cd.. In separate cell if used

from lib.network_mapper import network_mapper_function
from lib.NR3 import NR3_function
#from lib.computeFTreal import computeFTrealfunction
#from lib.computeJTreal import computeJTrealfunction
#from lib import *
import numpy as np
import math
import matplotlib.pyplot as plt
#matplotlib inline
fig_size = np.array([18, 6])
plt.rcParams["figure.figsize"] = fig_size

# z = exp(s*T)

# zoh
# z ~ 1 + s*T
# s ~ (z - 1)/T

# bilinear transform
# z ~ (2 + sT)/(2 - sT)
# s ~ (2/T)(z - 1)/(z + 1)

In [4]:
fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/NETWORKS/'
fn = '03node_fullphase_radial_example.txt'
#fn = '05node_fullphase_radial.txt'

#fn = '05node_fullphase_radial.txt'

network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 0.75*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.15*np.ones((3,nnode1))*(network1.loads.spu != 0)

network1.loads.aPQ = 1.00*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode1))*(network1.loads.spu != 0)

#network1.loads.spu = 1.25*network1.loads.spu

# Capacitor parameters

network1.caps.cappu = 1*network1.caps.cappu

# Controller parameters

network1.cons.wmaxpu = 0.5*network1.cons.wmaxpu


BASE
Vbase: 1.0
Sbase: 10.0
Ibase: 10.0
Zbase: 0.1

NODES
nnode: 4
nodelist: ['A0', 'A1', 'A2', 'A3']
phases: ['abc', 'abc', 'abc', 'abc']
PH:
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

LINES
nline: 3
TXnode: ['A0', 'A1', 'A1']
RXnode: ['A1', 'A2', 'A3']
TXnum: [0 1 1]
RXnum: [1 2 3]
phases: ['abc', 'abc', 'abc']
PH:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
config: ['12', '12', '12']
length: [0.0005 0.001  0.001 ]

NODES + LINES
inlines:
 [[-1  0  1  2]]
innodes:
 [[-1  0  1  1]]
outlines:
 [[ 0  1 -1 -1]
 [-1  2 -1 -1]]
outnodes:
 [[ 1  2 -1 -1]
 [-1  3 -1 -1]]

CONFIGS
nconf: 1
conflist: ['12']
12 - FZpl:
 [[10. +25.j  1.5 +5.j  1.5 +5.j]
 [ 1.5 +5.j 10. +30.j  1.5 +5.j]
 [ 1.5 +5.j  1.5 +5.j 10. +30.j]]

IMPEDANCE
0 - FZpu:
 [[0.005  +0.0125j 0.00075+0.0025j 0.00075+0.0025j]
 [0.00075+0.0025j 0.005  +0.015j  0.00075+0.0025j]
 [0.00075+0.0025j 0.00075+0.0025j 0.005  +0.015j ]]
1 - FZpu:
 [[0.01  +0.025j 0.0015+0.005j 0.0015+0.005j]
 [0.0015+0.005j 0.01  +0.03j  0.0015+0.005j]
 [0.0015+0.005j 0.0015+0.0

In [3]:
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)

'''
VNR = np.round(VNR,decimals=6)
INR = np.round(INR,decimals=6)
STXNR = np.round(STXNR,decimals=6)
SRXNR = np.round(SRXNR,decimals=6)
iNR = np.round(iNR,decimals=6)
sNR = np.round(sNR,decimals=6)
'''

print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

VNR
 [[ 1.      +0.      j  0.997548-0.004932j  0.986765-0.018654j
   0.985754-0.019026j  0.98569 -0.019068j  0.      +0.      j
   0.      +0.      j  0.979433-0.036155j  0.979414-0.036464j
   0.977261-0.037844j  0.979372-0.036201j  0.978755-0.036267j
   0.976856-0.035754j  0.      +0.      j]
 [-0.5     -0.866025j -0.502299-0.862002j -0.508107-0.85141 j
  -0.508015-0.850702j -0.508037-0.850662j -0.506552-0.846693j
  -0.506111-0.84509 j -0.511322-0.853831j -0.511346-0.854015j
  -0.512587-0.854155j -0.511354-0.853763j  0.      +0.      j
   0.      +0.      j  0.      +0.      j]
 [-0.5     +0.866025j -0.4945  +0.866059j -0.475702+0.860337j
  -0.475244+0.859589j -0.475203+0.859556j -0.475751+0.861657j
  -0.47579 +0.862098j -0.458176+0.851589j -0.457963+0.851421j
  -0.457677+0.850847j -0.458098+0.851563j -0.457327+0.851285j
   0.      +0.      j -0.456254+0.85111 j]]
INR
 [[ 2.33709e-01-0.091078j  2.33709e-01-0.091078j  3.18410e-02-0.02281 j
   3.18410e-02-0.02281 j  0.00000e+00+0.     

In [4]:
fid = open('NR3-' + fn[:-4] + '-python.txt','w')

phstr = ['a','b','c']

fid.write('VNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nnode):
        wstr = '{0:.6f}'.format(VNR[ph,k1].real) + ' ' + '{0:.6f}'.format(VNR[ph,k1].imag) + '\n'
        fid.write(wstr)

fid.write('\n\nINR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nline):
        wstr = '{0:.6f}'.format(INR[ph,k1].real) + ' ' + '{0:.6f}'.format(INR[ph,k1].imag) + '\n'
        fid.write(wstr)
        
fid.write('\n\nSTXNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nline):
        wstr = '{0:.6f}'.format(STXNR[ph,k1].real) + ' ' + '{0:.6f}'.format(STXNR[ph,k1].imag) + '\n'
        fid.write(wstr)

fid.write('\n\nSRXNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nline):
        wstr = '{0:.6f}'.format(SRXNR[ph,k1].real) + ' ' + '{0:.6f}'.format(SRXNR[ph,k1].imag) + '\n'
        fid.write(wstr)
        
fid.write('\n\niNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nnode):
        wstr = '{0:.6f}'.format(iNR[ph,k1].real) + ' ' + '{0:.6f}'.format(iNR[ph,k1].imag) + '\n'
        fid.write(wstr)
        
fid.write('\n\nsNR\n\n')
for ph in range(0,3):
    wstr = phstr[ph] + '\n'
    fid.write(wstr)
    for k1 in range(0,nnode):
        wstr = '{0:.6f}'.format(sNR[ph,k1].real) + ' ' + '{0:.6f}'.format(sNR[ph,k1].imag) + '\n'
        fid.write(wstr)

fid.close()