In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import pandas as pdk
import re
import sys
import time
import scipy.linalg as spla
from lib.compute_KCL_matrices import compute_KCL_matrices
from lib.basematricesY import basematrices as BM1
from lib.basematrices import basematrices as BM 
from lib.NR3_Y import NR3_timevarying as n1
from lib.NR3_timevarying import NR3_timevarying as n

Original NR3

In [2]:
t0 = time.time()
slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

#fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
#fn = '06node_threephase_radial_unbalanced.dss'
#fn = 'IEEE_13Node_Modified_01.dss'
fn = '02node_threephase_unbalanced_new.dss'
#fn = '06node_threephase_meshed_unbalanced.dss'
times = [-1]
der = [0]
capacitance =[0]

X, g_SB, b_SB, G_KVL, b_KVL, H, g, b = BM(fn, slackidx, Vslack, None, None)

   
dss.run_command('Redirect ' + fn)
nnode = len(dss.Circuit.AllBusNames())
nline = len(dss.Lines.AllNames())

VNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
INR01=  np.zeros((len(times), 3, nline), dtype = "complex")
STXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
SRXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
iNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
sNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")

t3 = time.time()

for _ in range(50):
    VNR = n(fn, X, g_SB, b_SB, G_KVL, b_KVL, H, g, b, None, None, 0, 0, -1)    
VNR01[0, :, :] = np.reshape(VNR, (3, nnode))

t2 = time.time()

Iteration number 0.000000
Iteration number 1.000000
VNR
[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]
Iteration number 0.000000
Iteration number 1.000000
VNR
[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]
Iteration number 0.000000
Iteration number 1.000000
VNR
[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]
Iteration number 0.000000
It

VNR
[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]
Iteration number 0.000000
Iteration number 1.000000
VNR
[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]
Iteration number 0.000000
Iteration number 1.000000
VNR
[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]
Iteration number 0.000000
Iteration number 1.000000
VNR
[[ 1.        +0.00000000

In [3]:
print('nr3',  t2-t3)
print( 'basematrices', t3 - t0)

nr3 0.5581362247467041
basematrices 0.014056921005249023


In [4]:
print(VNR)

[[ 1.        +0.00000000e+00j  0.99999999-4.54546584e-09j
   0.99999997-9.09093169e-09j]
 [-0.5       -8.66025404e-01j -0.5       -8.66025390e-01j
  -0.49999999-8.66025376e-01j]
 [-0.5       +8.66025404e-01j -0.49999999+8.66025394e-01j
  -0.49999998+8.66025385e-01j]]


Adjusted NR3

In [5]:
t0 = time.time()
slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

#fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
#fn = '06node_threephase_radial_unbalanced.dss'
#fn = 'IEEE_13Node_Modified_01.dss'
fn = '02node_threephase_unbalanced_new.dss'
#fn = '06node_threephase_meshed_unbalanced.dss'
times = [-1]
der = [0]
capacitance =[0]

X, g_SB, b_SB, H, g, b = BM1(fn, slackidx, Vslack, None, None)
 
dss.run_command('Redirect ' + fn)
nnode = len(dss.Circuit.AllBusNames())
nline = len(dss.Lines.AllNames())

VNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
INR01=  np.zeros((len(times), 3, nline), dtype = "complex")
STXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
SRXNR01 = np.zeros((len(times), 3, nline), dtype = "complex")
iNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")
sNR01 = np.zeros((len(times), 3, nnode), dtype = "complex")

t3 = time.time()
for _ in range(50):
    # Run NR3 with variations in time, DER, and capacitance
# VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    VNR = n1(fn, X, g_SB, b_SB, H, g, b, None, None, 0, 0, -1)    
VNR01[0, :, :] = np.reshape(VNR, (3, nnode))

t2 = time.time()

[[0.    0.125 0.1  ]
 [0.    0.1   0.125]
 [0.    0.075 0.1  ]]
[[0.    0.03  0.02 ]
 [0.    0.04  0.025]
 [0.    0.05  0.02 ]]
[[0.   0.   0.02]
 [0.   0.   0.02]
 [0.   0.   0.02]]
Iteration number 0.000000
Iteration number 1.000000
Iteration number 2.000000
Iteration number 3.000000
VNR
[[ 1.        +0.j          0.98448377+0.00416667j  0.96896754+0.00833333j]
 [-0.5       -0.8660254j  -0.48863345-0.85467129j -0.47726689-0.84331717j]
 [-0.5       +0.8660254j  -0.49585032+0.85050462j -0.49170065+0.83498384j]]
Iteration number 0.000000
Iteration number 1.000000
Iteration number 2.000000
Iteration number 3.000000
VNR
[[ 1.        +0.j          0.98448377+0.00416667j  0.96896754+0.00833333j]
 [-0.5       -0.8660254j  -0.48863345-0.85467129j -0.47726689-0.84331717j]
 [-0.5       +0.8660254j  -0.49585032+0.85050462j -0.49170065+0.83498384j]]
Iteration number 0.000000
Iteration number 1.000000
Iteration number 2.000000
Iteration number 3.000000
VNR
[[ 1.        +0.j          0.98448377+0.0

Iteration number 2.000000
Iteration number 3.000000
VNR
[[ 1.        +0.j          0.98448377+0.00416667j  0.96896754+0.00833333j]
 [-0.5       -0.8660254j  -0.48863345-0.85467129j -0.47726689-0.84331717j]
 [-0.5       +0.8660254j  -0.49585032+0.85050462j -0.49170065+0.83498384j]]
Iteration number 0.000000
Iteration number 1.000000
Iteration number 2.000000
Iteration number 3.000000
VNR
[[ 1.        +0.j          0.98448377+0.00416667j  0.96896754+0.00833333j]
 [-0.5       -0.8660254j  -0.48863345-0.85467129j -0.47726689-0.84331717j]
 [-0.5       +0.8660254j  -0.49585032+0.85050462j -0.49170065+0.83498384j]]
Iteration number 0.000000
Iteration number 1.000000
Iteration number 2.000000
Iteration number 3.000000
VNR
[[ 1.        +0.j          0.98448377+0.00416667j  0.96896754+0.00833333j]
 [-0.5       -0.8660254j  -0.48863345-0.85467129j -0.47726689-0.84331717j]
 [-0.5       +0.8660254j  -0.49585032+0.85050462j -0.49170065+0.83498384j]]
Iteration number 0.000000
Iteration number 1.00000

In [6]:
print(VNR)

[[ 1.        +0.j          0.98448377+0.00416667j  0.96896754+0.00833333j]
 [-0.5       -0.8660254j  -0.48863345-0.85467129j -0.47726689-0.84331717j]
 [-0.5       +0.8660254j  -0.49585032+0.85050462j -0.49170065+0.83498384j]]


In [7]:
print('nr3',  t2-t3)
print( 'basematrices', t3 - t0)

nr3 0.6324179172515869
basematrices 0.01897907257080078


OpenDSS Solution

In [13]:
#dss.run_command('Redirect compare_opendss_05node_threephase_unbalanced_oscillation_03.dss')
#dss.run_command('Redirect 06node_threephase_unbalanced.dss') 
#dss.run_command('Redirect IEEE_13Node_Modified_01.dss')
dss.run_command('Redirect 06node_threephase_meshed_unbalanced.dss')
dss.run_command('Redirect 02node_threephase_unbalanced_new.dss')

VDSS0 = np.zeros((len(times), 3, nnode), dtype = "complex")
IDSS0 =  np.zeros((len(times), 3, nline), dtype="complex")
SRXDSS0 = np.zeros((len(times), 3, nline), dtype="complex")
STXDSS0 = np.zeros((len(times), 3, nline), dtype="complex")
load_arr = np.zeros((len(times), 3, nnode), dtype='complex')

dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[0])
Vbase = dss.Bus.kVBase() * 1000
Sbase = 1000000.0
Ibase = Sbase/Vbase
Zbase = Vbase/Ibase

# Set slack bus (sourcebus) voltage reference in p.u.
SlackBusVoltage = 1.000
dss.Vsources.PU(SlackBusVoltage)

dss.Solution.Convergence(0.000000000001)
t4 = time.time()
# Solve power flow with OpenDSS file
for _ in range(50):
    dss.Solution.Solve()
    if not dss.Solution.Converged:
        print('Initial Solution Not Converged. Check Model for Convergence')
    else:
        print('Initial Model Converged. Proceeding to Next Step.')
        #Doing this solve command is required for GridPV, that is why the monitors
        #go under a reset process
        dss.Monitors.ResetAll()

        # set solution Params
        #setSolutionParams(dss,'daily',1,1,'off',1000000,30000)
        dss.Solution.Mode(1)
        dss.Solution.Number(1)
        dss.Solution.StepSize(1)
        dss.Solution.ControlMode(-1)
        dss.Solution.MaxControlIterations(1000000)
        dss.Solution.MaxIterations(30000)
        # Easy process to get all names and count of loads, a trick to avoid
        # some more lines of code
        TotalLoads=dss.Loads.Count()
        AllLoadNames=dss.Loads.AllNames()
        print('OpenDSS Model Compliation Done.')
        print('Iterations: ', dss.Solution.Iterations())
        print('Tolerance: ', dss.Solution.Convergence())

    print('')

t5=time.time()
print(dss.Solution.Converged())

# Print number of buses, and bus names
print(len(dss.Circuit.AllBusNames()))
print(dss.Circuit.AllBusNames())

# Print number of loads, and load names
print(len(dss.Loads.AllNames()))
print(dss.Loads.AllNames())

print('')

VDSS = np.zeros((3,len(dss.Circuit.AllBusNames())),dtype='complex')

for k1 in range(len(dss.Circuit.AllBusNames())):

    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[k1])

#     print(dss.Circuit.AllBusNames()[k1])
#     print(dss.Bus.Nodes())

#     print('puVOTLAGES - LN CARTESIAN')
#     print(dss.Bus.PuVoltage())

    ph = np.asarray(dss.Bus.Nodes(),dtype='int')-1

    Vtemp = np.asarray(dss.Bus.PuVoltage())

    Vtemp = Vtemp[0:nnode*2-1:2] + 1j*Vtemp[1:nnode*2:2]


#     print(np.asarray(dss.Bus.Nodes(),'int'))

    VDSS[ph,k1] = Vtemp    

#     VDSS[np.asarray(dss.Bus.Nodes(),'int'),k1] = np.array(dss.Bus.PuVoltage()[0:5:2] + 1j*dss.Bus.PuVoltage()[1:6:2])


#     VDSS[dss.Bus.Nodes()-1,k1] = dss.Bus.PuVoltage()[0:2:5]
#     for k2 in range(len(dss.Bus.Nodes())):
#         VDSS[int(dss.Bus.Nodes()[k2])-1,k1] = dss.Bus.PuVoltage()[2*k2] + 1j*dss.Bus.PuVoltage()[2*k2+1]

    print('VDSS\n', np.round(VDSS,decimals=6))
VDSS0[0, :, :] = VDSS

#     IDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

#     for k1 in range(len(dss.Lines.AllNames())):
#         dss.Lines.Name(dss.Lines.AllNames()[k1])
#     #     print(dss.Lines.AllNames()[k1])
#         ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
#         Imn = np.asarray(dss.CktElement.Currents())/Ibase
#     #     print(Imn)
#         Imn = Imn[0:int(len(Imn)/2)]
#     #     print(Imn)
#         Imn = Imn[0:(len(ph)*2)-1:2] + 1j*Imn[1:len(ph)*2:2]
#     #     print(Imn)
#         IDSS[ph,k1] = Imn
#     #     print('')

#     print('IDSS\n', np.round(IDSS,decimals=6))

#     STXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')
#     SRXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

#     for k1 in range(len(dss.Lines.AllNames())):
#         dss.Lines.Name(dss.Lines.AllNames()[k1])
#         ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
#         Sk = np.asarray(dss.CktElement.Powers())/(Sbase/1000)

#         STXtemp = Sk[0:int(len(Sk)/2)]
#         SRXtemp = Sk[int(len(Sk)/2):]

#         STXtemp = STXtemp[0:len(ph)*2-1:2] + 1j*STXtemp[1:len(ph)*2:2]
#         SRXtemp = -(SRXtemp[0:len(ph)*2-1:2] + 1j*SRXtemp[1:len(ph)*2:2])

#         STXDSS[ph,k1] = STXtemp
#         SRXDSS[ph,k1] = SRXtemp

    #VDSS0[i, :, :] = VDSS
#     IDSS0[i, :, :] = IDSS
#     SRXDSS0[i, :, :] = SRXDSS
#     STXDSS0[i, :, :] = STXDSS


#     print('STXDSS\n', np.round(STXDSS,decimals=6))
#     print('SRXDSS\n', np.round(SRXDSS,decimals=6))

#     print('|VDSS|\n', np.round(np.abs(VDSS),decimals=6))
#     print('<VDSS\n', np.round(180/np.pi*np.angle(VDSS),decimals=6))
#     print('D<VDSS\n', 180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VDSS[:,[0]]))


Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  2
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliat

In [14]:
t5-t4

0.08283638954162598

In [15]:
VDSS0[0]

array([[ 0.99999876-3.14048088e-06j,  0.99969436+7.17289049e-04j,
         0.99949187+1.16940518e-03j],
       [-0.50000194-8.66022548e-01j, -0.49934093-8.66485906e-01j,
        -0.49896191-8.66507016e-01j],
       [-0.49999725+8.66025434e-01j, -0.50072095+8.65528053e-01j,
        -0.50105444+8.65335844e-01j]])

In [16]:
VNR01[0]

array([[ 1.        +0.j        ,  0.98448377+0.00416667j,
         0.96896754+0.00833333j],
       [-0.5       -0.8660254j , -0.48863345-0.85467129j,
        -0.47726689-0.84331717j],
       [-0.5       +0.8660254j , -0.49585032+0.85050462j,
        -0.49170065+0.83498384j]])

Comparing results between three solutions - DSS, 01 (vectorized), 02 (nonvectorized)

In [12]:
for i in range(len(times)):
    print("Timestep %d \n" % i)
    print('Complex Voltage difference')
    #print(np.max(np.abs(VNR01[i] - VNR02[i])))
    print(np.max(np.abs(VDSS0[i] - VNR01[i]))) 

#     print('Complex Current difference')
#     print(np.max(np.abs(IDSS0[i] - INR01[i])))
    
#     print('Complex TX Power difference')
#     print(np.max(np.abs(STXDSS0[i] - STXNR01[i])))
    
#     print('Complex RX Power difference')
#     print(np.max(np.abs(SRXDSS0[i] - SRXNR01[i])))
    
#     print('Voltage Magnitude difference')
#     print(np.max(np.abs(np.abs(VDSS0[i]) - np.abs(VNR01[i]))))
    
#     print('Voltage Angle difference')
#     print(np.max(np.abs(180/np.pi*np.angle(VDSS0[i]) - 180/np.pi*np.angle(VNR01[i]))))
#     print("\n")

Timestep 0 

Complex Voltage difference
0.03176062897825715


In [ ]:
np.abs(VDSS0[0]-VNR01[0])
print(np.abs(VNR01[0]))

Load comparison between non-vectorized and OpenDSS

In [ ]:
for i in range(len(times)):
    print("Timestep %d \n Magnitude of the Difference: \n" % i)
    print(np.abs(spah[i] - load_arr[i]))
    print("Max difference: \n ")
    print(np.max(np.abs(spah[i] - load_arr[i])))
    print("\n")

In [ ]:
dss.run_command('Redirect IEEE_13Node_Modified_01.dss')
dss.run_command('Redirect 02node_threephase_unbalanced_new.dss')
for i in range(len(dss.Loads.AllNames())):
    dss.Loads.Name(dss.Loads.AllNames()[i])
    print(dss.Loads.kW())
    print(dss.Loads.kvar())
    print(dss.CktElement.Powers())

---

In [ ]:
t = -1
def load_order_f():
    load_order = {}
    for n in range(len(dss.Loads.AllNames())):
        dss.Loads.Name(dss.Loads.AllNames()[n])
        pattern =  r"(\w+)\."
        load_bus = re.findall(pattern, dss.CktElement.BusNames()[0])
        if load_bus[0] not in load_order:
            load_order[load_bus[0]] = 1
        elif load_bus[0] in load_order:
            load_order[load_bus[0]] += 1
    return load_order
load_order_list = load_order_f()

def load_values():
    load_ph_arr = np.zeros((nnode, max(load_order_list.values()), 3))
    load_kw_arr_ph = np.zeros((3, nnode))
    load_kvar_arr_ph = np.zeros((3, nnode))
    if t == -1:
        var = 1
    else:
        var = (1 + 0.1*np.sin(2*np.pi*0.01*t))
    for load in range(len(dss.Loads.AllNames())):
        dss.Loads.Name(dss.Loads.AllNames()[load])
        load_data = dss.CktElement.BusNames()[0].split('.')
        idxbs = dss.Circuit.AllBusNames().index(load_data[0])
        for ph in range(1, len(load_data)):
            load_kw_arr_ph[int(load_data[ph]) - 1, idxbs] += dss.Loads.kW() * 1e3 / Sbase / (len(load_data) - 1)
            load_kvar_arr_ph[int(load_data[ph]) - 1, idxbs] += dss.Loads.kvar() * 1e3 / Sbase / (len(load_data) - 1) 
    return load_kw_arr_ph, load_kvar_arr_ph
load_kw_arr_ph, load_kvar_arr_ph = load_values()
print(load_kw_arr_ph)
print(load_kvar_arr_ph)

In [ ]:

            idxbs = dss.Circuit.AllBusNames().index(cap_data[0])
            for ph in range(1, len(cap_data)):
                caparr[int(cap_data[ph]) - 1, idxbs] += dss.Capacitors.kvar() * 1e3 / Sbase / (len(cap_data) - 1)
        return caparr

In [ ]:
[[0.         0.         0.10384609 0.10384609 0.10384609 0.15576913
  0.        ]
 [0.         0.         0.10384609 0.10384609 0.         0.10384609
  0.05192304]
 [0.         0.         0.10384609 0.10384609 0.10384609 0.
  0.        ]]
[[0.         0.         0.02596152 0.02596152 0.02596152 0.05192304
  0.        ]
 [0.         0.         0.02596152 0.02596152 0.         0.02596152
  0.02596152]
 [0.         0.         0.02596152 0.02596152 0.02596152 0.
  0.        ]]