In [5]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.NR3_OpenDSSvec import NR3_function

In [6]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\NETWORKS\\"
fn = 'compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'

In [7]:
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = .750*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.15*np.ones((3,nnode1))*(network1.loads.spu != 0)


network1.loads.spu = 1.25*network1.loads.spu

BASE
Vbase: 2771.28
Sbase: 1000000.0
Ibase: 360.84408648711064
Zbase: 7.6799928384000005

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195313+0.00130208j 0.00065104+0.00520834

In [8]:
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1,slackidx,Vslack,None,None,None,None)

'''
VNR = np.round(VNR,decimals=6)
INR = np.round(INR,decimals=6)
STXNR = np.round(STXNR,decimals=6)
SRXNR = np.round(SRXNR,decimals=6)
iNR = np.round(iNR,decimals=6)
sNR = np.round(sNR,decimals=6)
'''

print('VNR\n', np.round(VNR,decimals=6))
print('INR\n', np.round(INR,decimals=6))
print('STXNR\n', np.round(STXNR,decimals=6))
print('SRXNR\n', np.round(SRXNR,decimals=6))
print('iNR\n', np.round(iNR,decimals=6))
print('sNR\n', np.round(sNR,decimals=6))
print('itercount:', itercount)

print('|VNR|\n', np.round(np.abs(VNR),decimals=6))
print('<VNR\n', np.round(180/np.pi*np.angle(VNR),decimals=6))
print('D<VNR\n', 180/np.pi*np.angle(VNR) - 180/np.pi*np.angle(VNR[:,[0]]))

[[ 0.        ]
 [ 0.        ]
 [-0.10625   ]
 [-0.02539062]
 [-0.10625   ]
 [-0.02539062]
 [-0.10625   ]
 [-0.02539062]
 [-0.10625   ]
 [-0.02539062]
 [-0.10625   ]
 [-0.02539062]
 [ 0.        ]
 [ 0.        ]
 [-0.10566406]
 [-0.02539062]
 [-0.10566406]
 [-0.02539062]
 [-0.10566406]
 [-0.02539062]
 [-0.10566406]
 [-0.02539062]
 [-0.10566406]
 [-0.02539062]
 [ 0.        ]
 [ 0.        ]
 [-0.11035156]
 [-0.0265625 ]
 [-0.11035156]
 [-0.0265625 ]
 [-0.11035156]
 [-0.0265625 ]
 [-0.11035156]
 [-0.0265625 ]
 [-0.11035156]
 [-0.0265625 ]]
[[-9.80928845e+24]
 [ 0.00000000e+00]
 [-1.07801953e+19]
 [ 2.31036302e+03]
 [-1.83259409e+10]
 [-4.19890324e+00]
 [-8.91198172e+07]
 [-3.90725563e+00]
 [ 3.77478133e+17]
 [ 3.41016701e-01]
 [-3.77477930e+17]
 [ 3.40971240e-01]
 [-7.58120943e+24]
 [ 0.00000000e+00]
 [ 1.24789645e+18]
 [-1.36263881e+01]
 [ 3.55708766e+15]
 [ 3.61577599e-01]
 [ 2.27253583e+15]
 [ 2.15797048e+00]
 [-4.71203333e+10]
 [ 1.80116764e+01]
 [-1.71881225e+11]
 [-3.88971590e+01]
 [-

In [5]:
print(nnode)
print(nline)

7
6


---
It's being weird.

In [6]:
dss.run_command('Redirect compare_opendss_05node_threephase_unbalanced_oscillation_03.dss')
dss.Solution.Solve()

In [6]:
def linelist(busname): #returns two lists of in and out lines at a bus
    in_lines = np.array([])
    out_lines = np.array([])
    for k in range(len(dss.Lines.AllNames())):
        dss.Lines.Name(dss.Lines.AllNames()[k])
        if busname in dss.Lines.Bus1():
            out_lines = np.append(out_lines, dss.Lines.AllNames()[k])
        elif busname in dss.Lines.Bus2():
            in_lines = np.append(in_lines, dss.Lines.AllNames()[k])
    return in_lines,out_lines

def get_line_idx(line): #returns the index of a line as stored in dss.Lines.AllNames()
    k = -1
    for n in range(len(dss.Lines.AllNames())):
        if dss.Lines.AllNames()[n] == line:
            k = n
    return k

In [7]:
get_line_idx([])

-1

In [8]:
for i in range(2):
    print('hello')
    print(i)

hello
0
hello
1
