In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
from lib.NR3 import NR3_function as NR31
from lib.compute_simultaneously import NR3_function as NR32
from lib.network_mapper_OpenDSSnonvec import network_mapper_function as nmf2
from lib.network_mapper import network_mapper_function as nmf

from math import tan,acos
import copy
import pandas as pd
import time
import re
import sys

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/NETWORKS/'
#fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
# fn = '02node_threephase_unbalanced.dss'
fn = 'lindist3flow_ieee13.txt'
network1 = nmf(fp, fn) #using LinDist3Flow config

nnode = network1.nodes.nnode
print('nnode: ', nnode)
nline = network1.lines.nline
print('nline: ', nline)

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


network1.loads.aPQ = 1.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)


# network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR01, INR01, STXNR01, SRXNR01, iNR01, sNR01, itercount01 = \
    NR31(network1,slackidx,Vslack,None,None,None,None)


print('VNR01\n', np.round(VNR01,decimals=6))
print('INR01\n', np.round(INR01,decimals=6))
print('STXNR01\n', np.round(STXNR01,decimals=6))
print('SRXNR01\n', np.round(SRXNR01,decimals=6))
print('iNR01\n', np.round(iNR01,decimals=6))
print('sNR01\n', np.round(sNR01,decimals=6))
print('itercount01:', itercount01)

print('|VNR01|\n', np.round(np.abs(VNR01),decimals=6))
print('<VNR01\n', np.round(180/np.pi*np.angle(VNR01),decimals=6))
print('D<VNR01\n', 180/np.pi*np.angle(VNR01) - 180/np.pi*np.angle(VNR01[:,[0]]))

BASE
Vbase: 2401.77711983
Sbase: 1000000.0
Ibase: 416.35836720385646
Zbase: 5.768533333338891

NODES
nnode: 15
nodelist: ['SUB', '671', '634', '645', '646', '692', '675', '611', '652', '670', '650', '632', '680', '633', '684']
phases: ['abc', 'abc', 'abc', 'bc', 'bc', 'abc', 'abc', 'c', 'a', 'abc', 'abc', 'abc', 'abc', 'abc', 'ac']
PH:
 [[1 1 1 0 0 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 0 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1]]

LINES
nline: 14
TXnode: ['SUB', '650', '632', '670', '671', '632', '633', '632', '645', '671', '692', '671', '684', '684']
RXnode: ['650', '632', '670', '671', '680', '633', '634', '645', '646', '692', '675', '684', '611', '652']
TXnum: [ 0 10 11  9  1 11 13 11  3  1  5  1 14 14]
RXnum: [10 11  9  1 12 13  2  3  4  5  6 14  7  8]
phases: ['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'bc', 'bc', 'abc', 'abc', 'ac', 'c', 'a']
PH:
 [[1 1 1 1 1 1 1 0 0 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0]]
config: ['mtx601', 'mtx601', 

VNR01
 [[ 1.      +0.j        0.918212-0.109575j  0.949417-0.055608j
   0.      +0.j        0.      +0.j        0.908985-0.113369j
   0.901697-0.117226j  0.      +0.j        0.910053-0.107582j
   0.943792-0.072183j  0.997897-0.002545j  0.95583 -0.053453j
   0.918212-0.109575j  0.952624-0.054531j  0.916031-0.109728j]
 [-0.5     -0.866025j -0.534497-0.851863j -0.517527-0.838974j
  -0.513366-0.833438j -0.512051-0.831318j -0.538984-0.85237j
  -0.542868-0.85267j   0.      +0.j        0.      +0.j
  -0.523115-0.845344j -0.500862-0.864938j -0.518098-0.843179j
  -0.534497-0.851863j -0.517812-0.841077j  0.      +0.j      ]
 [-0.5     +0.866025j -0.381057+0.806614j -0.426078+0.830691j
  -0.425877+0.835231j -0.424143+0.833954j -0.380096+0.803297j
  -0.379199+0.801376j -0.374805+0.804651j  0.      +0.j
  -0.410902+0.825428j -0.496611+0.864576j -0.428834+0.835579j
  -0.381057+0.806614j -0.427456+0.833135j -0.378309+0.805455j]]
INR01
 [[ 1.303428-0.683496j  1.303428-0.683496j  1.142243-0.558195j
   

In [3]:
network1 = nmf2('IEEE_13Node_Modified_01.dss', -1)
#network1 = network_mapper_function('compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.dss')

nnode = network1.nodes.nnode
nline = network1.lines.nline

nnode = network1.nodes.nnode
print('nnode: ', nnode)
nline = network1.lines.nline
print('nline: ', nline)

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

# network1.loads.aPQ = .750*np.ones((3,nnode))*(network1.loads.spu != 0)
# network1.loads.aI = 0.10*np.ones((3,nnode))*(network1.loads.spu != 0)
# network1.loads.aZ = 0.15*np.ones((3,nnode))*(network1.loads.spu != 0)

network1.loads.aPQ = 1.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)

# network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

fn = 'IEEE_13Node_Modified_01.dss'
VNR02, iNR02, sNR02, STXNR02, SRXNR02, INR02,itercount02 = NR32(network1, fn, slackidx,Vslack,None,None,None,None) #using OpenDSS as network object


# VNR02, INR02, STXNR02, SRXNR02, iNR02, sNR02, itercount02 = \
#     NR31(network1,slackidx,Vslack,None,None,None,None)


print('VNR02\n', np.round(VNR02,decimals=6))
print('INR02\n', np.round(INR02,decimals=6))
print('STXNR02\n', np.round(STXNR02,decimals=6))
print('SRXNR02\n', np.round(SRXNR02,decimals=6))
print('iNR02\n', np.round(iNR02,decimals=6))
print('sNR02\n', np.round(sNR02,decimals=6))
print('itercount02:', itercount02)

print('|VNR02|\n', np.round(np.abs(VNR02),decimals=6))
print('<VNR02\n', np.round(180/np.pi*np.angle(VNR02),decimals=6))
print('D<VNR02\n', 180/np.pi*np.angle(VNR02) - 180/np.pi*np.angle(VNR02[:,[0]]))

BASE
Vbase: 2401.7771198288433
Sbase: 1000000.0
Ibase: 416.358367204057
Zbase: 5.768533333333334

NODES
nnode: 15
nodelist: ['sourcebus', '671', '634', '645', '646', '692', '675', '611', '652', '670', '650', '632', '680', '633', '684']
phases: ['abc', 'abc', 'abc', 'bc', 'bc', 'abc', 'abc', 'c', 'a', 'abc', 'abc', 'abc', 'abc', 'abc', 'ac']
PH:
 [[1 1 1 0 0 1 1 0 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 0 0 1 1 1 1 1 0]
 [1 1 1 1 1 1 1 1 0 1 1 1 1 1 1]]
LINES
nline: 14
TXnode: ['sourcebus', '650', '632', '670', '671', '632', '633', '632', '645', '671', '692', '671', '684', '684']
RXnode: ['650', '632', '670', '671', '680', '633', '634', '645', '646', '692', '675', '684', '611', '652']
TXnum: [ 0 10 11  9  1 11 13 11  3  1  5  1 14 14]
RXnum: [10 11  9  1 12 13  2  3  4  5  6 14  7  8]
phases: ['abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'abc', 'bc', 'bc', 'abc', 'abc', 'ac', 'c', 'a']
PH:
 [[1 1 1 1 1 1 1 0 0 1 1 1 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 0]]
config: ['mtx60


LOADS
aPQ:
 [[0. 1. 1. 0. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 0. 0.]]
aI:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
aZ:
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
ppu:
 [[0.    0.385 0.16  0.    0.    0.085 0.485 0.    0.128 0.017 0.    0.
  0.    0.    0.   ]
 [0.    0.385 0.12  0.17  0.115 0.    0.068 0.    0.    0.066 0.    0.
  0.    0.    0.   ]
 [0.    0.385 0.12  0.    0.115 0.085 0.29  0.17  0.    0.117 0.    0.
  0.    0.    0.   ]]
qpu:
 [[0.     0.22   0.11   0.     0.     0.0755 0.19   0.     0.086  0.01
  0.     0.     0.     0.     0.    ]
 [0.     0.22   0.09   0.125  0.066  0.     0.06   0.     0.     0.038
  0.     0.     0.     0.     0.    ]
 [0.     0.22   0.09   0.     0.066 

In [4]:
Vbase = 2401.7771198288433
Sbase = 1000000.0
Ibase = Sbase/Vbase
Zbase = Vbase/Ibase

print(Ibase)
print(Zbase)

dss.run_command('Redirect IEEE_13Node_Modified_01.dss') #Using OpenDSS

# Set slack bus (sourcebus) voltage reference in p.u.
SlackBusVoltage = 1.000
dss.Vsources.PU(SlackBusVoltage)

dss.Solution.Convergence(0.000000000001)

# Solve power flow with OpenDSS file
dss.Solution.Solve()
if not dss.Solution.Converged:
    print('Initial Solution Not Converged. Check Model for Convergence')
else:
    print('Initial Model Converged. Proceeding to Next Step.')
    #Doing this solve command is required for GridPV, that is why the monitors
    #go under a reset process
    dss.Monitors.ResetAll()
    
    #set solution Params
    #setSolutionParams(dss,'daily',1,1,'off',1000000,30000)
    dss.Solution.Mode(1)
    dss.Solution.Number(1)
    dss.Solution.StepSize(1)
    dss.Solution.ControlMode(-1)
    dss.Solution.MaxControlIterations(1000000)
    dss.Solution.MaxIterations(30000)
    #Easy process to get all names and count of loads, a trick to avoid
    #some more lines of code
    TotalLoads=dss.Loads.Count()
    AllLoadNames=dss.Loads.AllNames()
    print('OpenDSS Model Compliation Done.')
    print('Iterations: ', dss.Solution.Iterations())
    print('Tolerance: ', dss.Solution.Convergence())

print('')

# print(dss.Solution.Converged())

# Print number of buses, and bus names
print(len(dss.Circuit.AllBusNames()))
print(dss.Circuit.AllBusNames())

# Print number of loads, and load names
print(len(dss.Loads.AllNames()))
print(dss.Loads.AllNames())

print('')

VDSS = np.zeros((3,len(dss.Circuit.AllBusNames())),dtype='complex')

for k1 in range(len(dss.Circuit.AllBusNames())):
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[k1])
#     print(dss.Circuit.AllBusNames()[k1])
#     print(dss.Bus.Nodes())

#     print('puVOTLAGES - LN CARTESIAN')
#     print(dss.Bus.PuVoltage())

    ph = np.asarray(dss.Bus.Nodes(),dtype='int')-1

    Vtemp = np.asarray(dss.Bus.PuVoltage())
    Vtemp = Vtemp[0:5:2] + 1j*Vtemp[1:6:2]
    
#     print(np.asarray(dss.Bus.Nodes(),'int'))
    
    VDSS[ph,k1] = Vtemp    
        
#     VDSS[np.asarray(dss.Bus.Nodes(),'int'),k1] = np.array(dss.Bus.PuVoltage()[0:5:2] + 1j*dss.Bus.PuVoltage()[1:6:2])
    
    
#     VDSS[dss.Bus.Nodes()-1,k1] = dss.Bus.PuVoltage()[0:2:5]
#     for k2 in range(len(dss.Bus.Nodes())):
#         VDSS[int(dss.Bus.Nodes()[k2])-1,k1] = dss.Bus.PuVoltage()[2*k2] + 1j*dss.Bus.PuVoltage()[2*k2+1]
        
print('VDSS\n', np.round(VDSS,decimals=6))


IDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

for k1 in range(len(dss.Lines.AllNames())):
    dss.Lines.Name(dss.Lines.AllNames()[k1])
#     print(dss.Lines.AllNames()[k1])
    ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
    Imn = np.asarray(dss.CktElement.Currents())/Ibase
#     print(Imn)
    Imn = Imn[0:int(len(Imn)/2)]
#     print(Imn)
    Imn = Imn[0:5:2] + 1j*Imn[1:6:2]
#     print(Imn)
    IDSS[ph,k1] = Imn
#     print('')

print('IDSS\n', np.round(IDSS,decimals=6))

STXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')
SRXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

for k1 in range(len(dss.Lines.AllNames())):
    dss.Lines.Name(dss.Lines.AllNames()[k1])
#     print(dss.Lines.AllNames()[k1])
#     print(dss.CktElement.BusNames())
    ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
#     print(ph)
    Sk = np.asarray(dss.CktElement.Powers())/(Sbase/1000)
#     print(Sk)
    
#     print(Sk[0:int(len(Sk)/2)])
#     print(Sk[int(len(Sk)/2):])
    
    STXtemp = Sk[0:int(len(Sk)/2)]
    SRXtemp = Sk[int(len(Sk)/2):]
    
    STXtemp = STXtemp[0:5:2] + 1j*STXtemp[1:6:2]
#     print(STXtemp)
    
    SRXtemp = -(SRXtemp[0:5:2] + 1j*SRXtemp[1:6:2])
#     print(SRXtemp)
    
    STXDSS[ph,k1] = STXtemp
    SRXDSS[ph,k1] = SRXtemp

print('STXDSS\n', np.round(STXDSS,decimals=6))
print('SRXDSS\n', np.round(SRXDSS,decimals=6))

print('|VDSS|\n', np.round(np.abs(VDSS),decimals=6))
print('<VDSS\n', np.round(180/np.pi*np.angle(VDSS),decimals=6))
print('D<VDSS\n', 180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VDSS[:,[0]]))

416.358367204057
5.768533333333334
Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  9
Tolerance:  1e-12

15
['sourcebus', '671', '634', '645', '646', '692', '675', '611', '652', '670', '650', '632', '680', '633', '684']
15
['671', '634a', '634b', '634c', '645', '646', '692', '675a', '675b', '675c', '611', '652', '670a', '670b', '670c']

VDSS
 [[ 0.999808-2.31000e-04j  0.878117-1.33969e-01j  0.931033-6.53090e-02j
   0.      +0.00000e+00j  0.      +0.00000e+00j  0.868665-1.39676e-01j
   0.863452-1.45725e-01j  0.      +0.00000e+00j  0.870902-1.32021e-01j
   0.918081-8.68860e-02j  0.996836-3.23700e-03j  0.93739 -6.33560e-02j
   0.878117-1.33969e-01j  0.934211-6.43320e-02j  0.876138-1.34097e-01j]
 [-0.50012 -8.65773e-01j -0.581687-7.94743e-01j -0.539743-8.02596e-01j
  -0.531896-7.91948e-01j -0.528455-7.86690e-01j -0.59088 -7.94882e-01j
  -0.598735-7.94674e-01j  0.      +0.00000e+00j  0.      +0.00000e+00j
  -0.553811-8.02101e-01j -0.502044-8.629

In [5]:
#dss - opendss solution
#01 - nonvectorized solution using LinDist3Flow file network mapper
#02 - nonvectorized solution using OpenDSS file network mapper
print('Complex Voltage difference')
print(np.max(np.abs(VNR01 - VNR02)))
print(np.max(np.abs(VDSS - VNR01))) 
print(np.max(np.abs(VDSS - VNR02)))

print('Complex Current difference')
print(np.max(np.abs(INR01 - INR02)))
print(np.max(np.abs(IDSS - INR01)))
print(np.max(np.abs(IDSS - INR02)))

print('Complex TX Power difference')
print(np.max(np.abs(STXNR01 - STXNR02)))
print(np.max(np.abs(STXDSS - STXNR01)))
print(np.max(np.abs(STXDSS - STXNR02)))

print('Complex RX Power difference')
print(np.max(np.abs(SRXNR01 - SRXNR02)))
print(np.max(np.abs(SRXDSS - SRXNR01)))
print(np.max(np.abs(SRXDSS - SRXNR02)))

print('Voltage Magnitude difference')
print(np.max(np.abs(np.abs(VNR01) - np.abs(VNR02))))
print(np.max(np.abs(np.abs(VDSS) - np.abs(VNR01))))
print(np.max(np.abs(np.abs(VDSS) - np.abs(VNR02))))

print('Voltage Angle difference')
print(np.max(np.abs(180/np.pi*np.angle(VNR01) - 180/np.pi*np.angle(VNR02))))
print(np.max(np.abs(180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VNR01))))
print(np.max(np.abs(180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VNR02))))

Complex Voltage difference
1.666574772473019e-13
0.08052695660098046
0.08052695660094313
Complex Current difference
2.3407008726900904e-13
0.840680107209405
0.840680107209408
Complex TX Power difference
2.3391619272437117e-13
0.840432058183733
0.8404320581837358
Complex RX Power difference
2.281465905231233e-13
0.8385939050734236
0.8385939050734267
Voltage Magnitude difference
1.2823075934420558e-13
0.03644962197472623
0.03644962197463941
Voltage Angle difference
8.243183913236862e-12
4.5120024091602176
4.512002409157773


In [6]:
print(VNR01.shape)
print(VNR02.shape)
print(VDSS.shape)

(3, 15)
(3, 15)
(3, 15)
