In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.NR3_OpenDSSvec_splitup import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\NETWORKS\\"
fn = 'compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI =0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)


network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'

BASE
Vbase: 2771.2799999999997
Sbase: 1000000.0
Ibase: 360.8440864871107
Zbase: 7.679992838399998

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195313+0.00130208j 0.00065104+0

In [3]:
slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

VNR, INR, STXNR, SRXNR, iNR, sNR, itercount = \
    NR3_function(network1, fn, slackidx,Vslack,None,None,None)

[[ 0.   ]
 [ 0.   ]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.1  ]
 [ 0.   ]
 [ 0.   ]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.1  ]
 [ 0.   ]
 [ 0.   ]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.075]
 [ 0.   ]
 [-0.1  ]]
[[ 0.       ]
 [ 0.       ]
 [ 0.       ]
 [ 0.       ]
 [-0.3660254]
 [-1.3660254]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
huuuh


LinAlgError: Singular matrix

In [4]:
dss.run_command('Redirect ' + fn)
dss.Solution.Solve()
for i in range(len(dss.Circuit.AllBusNames())):
    #print(dss.Circuit.AllBusNames()[i])
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[i])
    print(dss.CktElement.Powers())
for j in range(len(dss.Lines.AllNames())):
    dss.Lines.Name(dss.Lines.AllNames()[j])
    print(dss.CktElement.Powers())
    print(len(dss.CktElement.Powers()))
    print("\n")

[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[99.99999996050043, 49.99999997507175, 0.0, 0.0]
[401.48505569740087, 97.85333621587914, 400.2663769723341, 123.30485406916362, 300.3431007675018, 73.39865764989095, -401.07928432216164, -98.49172082589838, -400.1729464236654, -123.86628021875867, -300.26220562716924, -73.91519993053859]
12


[401.07928432238316, 98.49172082596425, 400.1729464235233, 123.86628021872413, 300.26220562726803, 73.91519993054918, -400.67350995173433, -99.13009871745558, -400.0795183525604, -124.42772086883613, -300.18130340966576, -74.4317517728465]
12


[300.6735099474505, 74.13009871626309, 300.0795183894979, 99.42772087802783, 200.18130337580814, 49.431751764389574, -300.1477712581612, -74.83366105810245, -300.02663

In [19]:
def get_power_based_on_bus(busname, cplx):
    
    dss.Circuit.SetActiveBus(busname)
   
    for j in range(len(dss.Loads.AllNames())):
        if dss.Circuit.AllBusNames()[n] in dss.Loads.AllNames()[j]:
            dss.Loads.Name(dss.Loads.AllNames()[j])
            if cplx == 0:
                return dss.Loads.kW()
            else:
                return dss.Loads.kvar()
        

        #print('hey')
get_power_based_on_bus(dss.Circuit.AllBusNames()[6], 1)

50.0