In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
from lib.NR3 import NR3_function as NR31
from lib.compute_simultaneously import NR3_function as NR32
from lib.network_mapper_OpenDSSnonvec import network_mapper_function as nmf2
from lib.network_mapper import network_mapper_function as nmf

from math import tan,acos
import copy
import pandas as pd
import time
import re
import sys

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/NETWORKS/'

fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
# fn = '02node_threephase_unbalanced.dss'
network1 = nmf(fp, fn) #using LinDist3Flow config

nnode = network1.nodes.nnode
print('nnode: ', nnode)
nline = network1.lines.nline
print('nline: ', nline)

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))


network1.loads.aPQ = 1.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)


# network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])


VNR01, INR01, STXNR01, SRXNR01, iNR01, sNR01, itercount01 = \
    NR31(network1,slackidx,Vslack,None,None,None,None)


print('VNR01\n', np.round(VNR01,decimals=6))
print('INR01\n', np.round(INR01,decimals=6))
print('STXNR01\n', np.round(STXNR01,decimals=6))
print('SRXNR01\n', np.round(SRXNR01,decimals=6))
print('iNR01\n', np.round(iNR01,decimals=6))
print('sNR01\n', np.round(sNR01,decimals=6))
print('itercount01:', itercount01)

print('|VNR01|\n', np.round(np.abs(VNR01),decimals=6))
print('<VNR01\n', np.round(180/np.pi*np.angle(VNR01),decimals=6))
print('D<VNR01\n', 180/np.pi*np.angle(VNR01) - 180/np.pi*np.angle(VNR01[:,[0]]))

BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
network1 = nmf2('compare_opendss_05node_threephase_unbalanced_oscillation_03.dss', -1)
#network1 = network_mapper_function('compare__lindist3flow_05node_threephase_unbalanced_oscillation_03.dss')

nnode = network1.nodes.nnode
nline = network1.lines.nline

nnode = network1.nodes.nnode
print('nnode: ', nnode)
nline = network1.lines.nline
print('nline: ', nline)

network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

# network1.loads.aPQ = .750*np.ones((3,nnode))*(network1.loads.spu != 0)
# network1.loads.aI = 0.10*np.ones((3,nnode))*(network1.loads.spu != 0)
# network1.loads.aZ = 0.15*np.ones((3,nnode))*(network1.loads.spu != 0)

network1.loads.aPQ = 1.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aI = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)
network1.loads.aZ = 0.00*np.ones((3,nnode))*(network1.loads.spu != 0)

# network1.loads.spu = 1.25*network1.loads.spu

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])

fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
VNR02, iNR02, sNR02, STXNR02, SRXNR02, INR02,itercount02 = NR32(network1, fn, slackidx,Vslack,None,None,None,None) #using OpenDSS as network object


# VNR02, INR02, STXNR02, SRXNR02, iNR02, sNR02, itercount02 = \
#     NR31(network1,slackidx,Vslack,None,None,None,None)


print('VNR02\n', np.round(VNR02,decimals=6))
print('INR02\n', np.round(INR02,decimals=6))
print('STXNR02\n', np.round(STXNR02,decimals=6))
print('SRXNR02\n', np.round(SRXNR02,decimals=6))
print('iNR02\n', np.round(iNR02,decimals=6))
print('sNR02\n', np.round(sNR02,decimals=6))
print('itercount02:', itercount02)

print('|VNR02|\n', np.round(np.abs(VNR02),decimals=6))
print('<VNR02\n', np.round(180/np.pi*np.angle(VNR02),decimals=6))
print('D<VNR02\n', 180/np.pi*np.angle(VNR02) - 180/np.pi*np.angle(VNR02[:,[0]]))

['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]
{'sourcebus': 0, 'a01': 1, 'a02': 2, 'a03': 3, 'a04': 4, 'a05': 5, 'a06': 6}
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[1, 0, 1]
[1, 1, 0]
[0, 1, 0]
LINES
nline: 6
TXnode: ['sourcebus', 'a01', 'a02', 'a03', 'a03', 'a05']
RXnode: ['a01', 'a02', 'a03', 'a04', 'a05', 'a06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2

In [4]:
Vbase = 2771.2812921102036
Sbase = 1000000.0
Ibase = Sbase/Vbase
Zbase = Vbase/Ibase

print(Ibase)
print(Zbase)

dss.run_command('Redirect compare_opendss_05node_threephase_unbalanced_oscillation_03.dss') #Using OpenDSS

# Set slack bus (sourcebus) voltage reference in p.u.
SlackBusVoltage = 1.000
dss.Vsources.PU(SlackBusVoltage)

dss.Solution.Convergence(0.000000000001)

# Solve power flow with OpenDSS file
dss.Solution.Solve()
if not dss.Solution.Converged:
    print('Initial Solution Not Converged. Check Model for Convergence')
else:
    print('Initial Model Converged. Proceeding to Next Step.')
    #Doing this solve command is required for GridPV, that is why the monitors
    #go under a reset process
    dss.Monitors.ResetAll()
    
    #set solution Params
    #setSolutionParams(dss,'daily',1,1,'off',1000000,30000)
    dss.Solution.Mode(1)
    dss.Solution.Number(1)
    dss.Solution.StepSize(1)
    dss.Solution.ControlMode(-1)
    dss.Solution.MaxControlIterations(1000000)
    dss.Solution.MaxIterations(30000)
    #Easy process to get all names and count of loads, a trick to avoid
    #some more lines of code
    TotalLoads=dss.Loads.Count()
    AllLoadNames=dss.Loads.AllNames()
    print('OpenDSS Model Compliation Done.')
    print('Iterations: ', dss.Solution.Iterations())
    print('Tolerance: ', dss.Solution.Convergence())

print('')

# print(dss.Solution.Converged())

# Print number of buses, and bus names
print(len(dss.Circuit.AllBusNames()))
print(dss.Circuit.AllBusNames())

# Print number of loads, and load names
print(len(dss.Loads.AllNames()))
print(dss.Loads.AllNames())

print('')

VDSS = np.zeros((3,len(dss.Circuit.AllBusNames())),dtype='complex')

for k1 in range(len(dss.Circuit.AllBusNames())):
    dss.Circuit.SetActiveBus(dss.Circuit.AllBusNames()[k1])
#     print(dss.Circuit.AllBusNames()[k1])
#     print(dss.Bus.Nodes())

#     print('puVOTLAGES - LN CARTESIAN')
#     print(dss.Bus.PuVoltage())

    ph = np.asarray(dss.Bus.Nodes(),dtype='int')-1

    Vtemp = np.asarray(dss.Bus.PuVoltage())
    Vtemp = Vtemp[0:5:2] + 1j*Vtemp[1:6:2]
    
#     print(np.asarray(dss.Bus.Nodes(),'int'))
    
    VDSS[ph,k1] = Vtemp    
        
#     VDSS[np.asarray(dss.Bus.Nodes(),'int'),k1] = np.array(dss.Bus.PuVoltage()[0:5:2] + 1j*dss.Bus.PuVoltage()[1:6:2])
    
    
#     VDSS[dss.Bus.Nodes()-1,k1] = dss.Bus.PuVoltage()[0:2:5]
#     for k2 in range(len(dss.Bus.Nodes())):
#         VDSS[int(dss.Bus.Nodes()[k2])-1,k1] = dss.Bus.PuVoltage()[2*k2] + 1j*dss.Bus.PuVoltage()[2*k2+1]
        
print('VDSS\n', np.round(VDSS,decimals=6))


IDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

for k1 in range(len(dss.Lines.AllNames())):
    dss.Lines.Name(dss.Lines.AllNames()[k1])
#     print(dss.Lines.AllNames()[k1])
    ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
    Imn = np.asarray(dss.CktElement.Currents())/Ibase
#     print(Imn)
    Imn = Imn[0:int(len(Imn)/2)]
#     print(Imn)
    Imn = Imn[0:5:2] + 1j*Imn[1:6:2]
#     print(Imn)
    IDSS[ph,k1] = Imn
#     print('')

print('IDSS\n', np.round(IDSS,decimals=6))

STXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')
SRXDSS = np.zeros((3,len(dss.Lines.AllNames())),dtype='complex')

for k1 in range(len(dss.Lines.AllNames())):
    dss.Lines.Name(dss.Lines.AllNames()[k1])
#     print(dss.Lines.AllNames()[k1])
#     print(dss.CktElement.BusNames())
    ph = np.asarray(dss.CktElement.BusNames()[0].split('.')[1:], dtype='int')-1
#     print(ph)
    Sk = np.asarray(dss.CktElement.Powers())/(Sbase/1000)
#     print(Sk)
    
#     print(Sk[0:int(len(Sk)/2)])
#     print(Sk[int(len(Sk)/2):])
    
    STXtemp = Sk[0:int(len(Sk)/2)]
    SRXtemp = Sk[int(len(Sk)/2):]
    
    STXtemp = STXtemp[0:5:2] + 1j*STXtemp[1:6:2]
#     print(STXtemp)
    
    SRXtemp = -(SRXtemp[0:5:2] + 1j*SRXtemp[1:6:2])
#     print(SRXtemp)
    
    STXDSS[ph,k1] = STXtemp
    SRXDSS[ph,k1] = SRXtemp

print('STXDSS\n', np.round(STXDSS,decimals=6))
print('SRXDSS\n', np.round(SRXDSS,decimals=6))

print('|VDSS|\n', np.round(np.abs(VDSS),decimals=6))
print('<VDSS\n', np.round(180/np.pi*np.angle(VDSS),decimals=6))
print('D<VDSS\n', 180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VDSS[:,[0]]))

360.8439182435161
7.68
Initial Model Converged. Proceeding to Next Step.
OpenDSS Model Compliation Done.
Iterations:  4
Tolerance:  1e-12

7
['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
11
['load_a02_a_01', 'load_a02_b_01', 'load_a02_c_01', 'load_a03_a_01', 'load_a03_b_01', 'load_a03_c_01', 'load_a04_a_01', 'load_a04_c_01', 'load_a05_a_01', 'load_a05_b_01', 'load_a06_b_01']

VDSS
 [[ 0.999997-5.00000e-06j  0.999403+1.70500e-03j  0.99881 +3.41500e-03j
   0.99769 +5.99000e-03j  0.998303+5.99700e-03j  0.996028+7.71100e-03j
   0.      +0.00000e+00j]
 [-0.500003-8.66020e-01j -0.498943-8.66833e-01j -0.497884-8.67647e-01j
  -0.496531-8.68907e-01j  0.      +0.00000e+00j -0.496629-8.68963e-01j
  -0.496427-8.68479e-01j]
 [-0.499995+8.66026e-01j -0.501495+8.65315e-01j -0.502995+8.64605e-01j
  -0.505297+8.63668e-01j -0.505311+8.62344e-01j  0.      +0.00000e+00j
   0.      +0.00000e+00j]]
IDSS
 [[ 0.401486-0.097856j  0.401486-0.097866j  0.301282-0.073188j
   0.100318-0.024431j  0.100586-

In [5]:
#dss - opendss solution
#01 - nonvectorized solution using LinDist3Flow file network mapper
#02 - vectorized solution using OpenDSS file
print('Complex Voltage difference')
print(np.max(np.abs(VNR01 - VNR02)))
print(np.max(np.abs(VDSS - VNR01))) 
print(np.max(np.abs(VDSS - VNR02)))

print('Complex Current difference')
print(np.max(np.abs(INR01 - INR02)))
print(np.max(np.abs(IDSS - INR01)))
print(np.max(np.abs(IDSS - INR02)))

print('Complex TX Power difference')
print(np.max(np.abs(STXNR01 - STXNR02)))
print(np.max(np.abs(STXDSS - STXNR01)))
print(np.max(np.abs(STXDSS - STXNR02)))

print('Complex RX Power difference')
print(np.max(np.abs(SRXNR01 - SRXNR02)))
print(np.max(np.abs(SRXDSS - SRXNR01)))
print(np.max(np.abs(SRXDSS - SRXNR02)))

print('Voltage Magnitude difference')
print(np.max(np.abs(np.abs(VNR01) - np.abs(VNR02))))
print(np.max(np.abs(np.abs(VDSS) - np.abs(VNR01))))
print(np.max(np.abs(np.abs(VDSS) - np.abs(VNR02))))

print('Voltage Angle difference')
print(np.max(np.abs(180/np.pi*np.angle(VNR01) - 180/np.pi*np.angle(VNR02))))
print(np.max(np.abs(180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VNR01))))
print(np.max(np.abs(180/np.pi*np.angle(VDSS) - 180/np.pi*np.angle(VNR02))))

Complex Voltage difference
3.1401849173675503e-16
6.712466223766493e-06
6.712466223765739e-06
Complex Current difference
1.1102230246251565e-16
4.481028617898973e-05
4.4810286179003603e-05
Complex TX Power difference
1.2412670766236366e-16
4.727777946085255e-05
4.7277779460866424e-05
Complex RX Power difference
8.326672684688674e-17
3.746231481517061e-05
3.746231481518449e-05
Voltage Magnitude difference
2.220446049250313e-16
3.6500538938000204e-06
3.6500538938000204e-06
Voltage Angle difference
2.842170943040401e-14
0.0003344079230399588
0.0003344079230399033


In [6]:
print(VNR01.shape)
print(VNR02.shape)
print(VDSS.shape)

(3, 7)
(3, 7)
(3, 7)
