In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function


In [3]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [4]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec = \
    NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [11]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(XNR_deep_vec.shape[2]):
    print(n)
    print(XNR_deep_vec[:,0,n] - XNR_deep_nonvec[:,0,n])
    print('')

n = 0
print(XNR_deep_vec[:,0,n] - XNR_deep_nonvec[:,0,n])

(78, 1, 4)
(78, 1, 4)
ft: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

2
[-0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446

In [12]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(len(FT_deep_vec[0][0])):
    print(n)
    print(FT_deep_vec[:, 0][:, n] - FT_deep_nonvec[:, 0][:, n])
    print('')

    


(78, 1, 4)
(78, 1, 4)
ft: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

2
[-4.64455710e-04  1.43798839e-04 -4.81395613e-05 -2.00452243e-04
 -2.35648316e-04 -2.37308912e-05  4.98278513e-04 -2.31948842e-04
  5.53131104e-04 -1.56402588e-04  2.01702118e-04  1.24740601e-03
  1.59454346e-03 -1.68228149e-03 -2.63541937e-04 -3.27202491e-04
  4.05531999e-08 -4.05532002e-08  2.44140625e-04  2.26974487e-04
 -6.06536865e-04  6.48498535e-05 -7.97271729e-04 -3.12805176e-04
 -2.00466991e-04 -6.28994911e-05  9.82745551e-04  4.57297079e-04
 -2.67028809e-04  6.21795654e-0

In [21]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[:,:,n] - JT_deep_nonvec[:,:,n])

(78, 78, 4)
(78, 78, 4)
jt: 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.

In [41]:
print('xnr: \n')
for n in range(len(XNR_deep_vec[0][0])): 
    print(XNR_deep_vec[:, 0][:, n] - XNR_deep_nonvec[:, 0][:, n])

xnr: 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]
[-0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.