In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 0.85*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.05*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_notvec, \
        FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
        FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
        JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
        JSUBV_vec, JKVL_vec, JKCL_vec = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

0
1
2
3
[[ 1.00000000e+00]
 [ 1.88693941e-26]
 [ 9.99406651e-01]
 [ 1.71073185e-03]
 [ 9.98813302e-01]
 [ 3.42146369e-03]
 [ 9.97694410e-01]
 [ 5.99682794e-03]
 [ 9.98307628e-01]
 [ 6.00433121e-03]
 [ 9.96032085e-01]
 [ 7.71884457e-03]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.00000000e-01]
 [-8.66025404e-01]
 [-4.98940060e-01]
 [-8.66837780e-01]
 [-4.97880120e-01]
 [-8.67650157e-01]
 [-4.96526772e-01]
 [-8.68909417e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.96624130e-01]
 [-8.68964280e-01]
 [-4.96422244e-01]
 [-8.68479929e-01]
 [-5.00000000e-01]
 [ 8.66025404e-01]
 [-5.01499840e-01]
 [ 8.65316447e-01]
 [-5.02999679e-01]
 [ 8.64607490e-01]
 [-5.05300953e-01]
 [ 8.63672169e-01]
 [-5.05315037e-01]
 [ 8.62348330e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 4.01302530e-01]
 [-9.78556704e-02]
 [ 4.01302530e-01]
 [-9.78556704e-02]
 [ 3.01122813e-01]
 [-7.31750457e-02]
 [ 1.00282934e-01]
 [-2.44308460e-02]
 [ 1.00507697e-01]
 [-2.43009499e-02]
 [-9

In [4]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# VNR, iNR, sNR, STXNR, SRXNR, INR = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [5]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
#             FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
#             FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
#             JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
#             JSUBV_vec, JKVL_vec, JKCL_vec \
#              = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [6]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# VNR, iNR, sNR, STXNR, SRXNR, INR = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [7]:
print(XNR_deep_notvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(4):
    print(n)
    print(XNR_deep_vec[n, :,0] - XNR_deep_notvec[n, :,0])
    print('')

n = 1
print(XNR_deep_vec[n, :,0] - XNR_deep_notvec[n, :,0])

(101, 78, 1)
(101, 78, 1)
XNR: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[ 0.00000000e+00  3.58575783e-18  8.18404985e-05 -5.56505676e-05
  1.63680997e-04 -1.11301135e-04  2.84880210e-04 -1.96895149e-04
  3.01656982e-04 -1.90834243e-04  3.46866510e-04 -2.62655265e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  2.01819872e-05  3.81314535e-05  4.03639744e-05  7.62629070e-05
  6.94499232e-05  1.33000494e-04  0.00000000e+00  0.00000000e+00
  7.28686570e-05  1.33315580e-04  6.51854123e-05  1.15056252e-04
  0.00000000e+00  0.00000000e+00  7.73775663e-05  6.58588467e-06
  1.54755133e-04  1.31717693e-05  2.69338112e-04  2.06508004e-05
  2.83920491e-04  5.79064857e-05  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.47021583e-02  3.73353902e-03
 -1.4702

In [ ]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(4):
    print(n)
    print(FT_deep_vec[n, :, :] - FT_deep_nonvec[n, :, :])
    print('')

In [ ]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[n, :,:] - JT_deep_nonvec[n, :,:])

In [ ]:
print('XNR: \n')
for n in range(4): 
    print(XNR_deep_vec[n, :, :] - XNR_deep_nonvec[n, :, :])
    print("\n ")

Split up FT and JT into SUBV, KVL and KCL

In [ ]:
print('ftsubv: \n')
print(FTSUBV_vec.shape)
for n in range(4): 
    print(FTSUBV_vec[n,:,:] - FTSUBV_nonvec[n, :, :])
    print("\n ")
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

In [ ]:
print('ftkvl: \n')
print(FTKVL_vec.shape)
for n in range(4): 
    print(FTKVL_vec[n, :, 0] - FTKVL_nonvec[n, :, 0])
    print("\n ")

In [ ]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(4): 
    print(FTKCL_vec[n, :, :] - FTKCL_nonvec[n, :, :])
    print("\n ")

In [ ]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(4): 
    print(n)
    print("\n")
    print(JSUBV_vec[n, :, :] - JSUBV_nonvec[n, :, :])


In [ ]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(4): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])
    print("\n ")


In [ ]:
print('JKCL: \n')
print(JKCL_vec.shape)
for n in range(4): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])
    print("\n ")
