In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 0.85*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.05*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
#         FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
#         FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
#         JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
#         JSUBV_vec, JKVL_vec, JKCL_vec = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [4]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
VNR, iNR, sNR, STXNR, SRXNR, INR, ic = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

0
1
2
3
VNR
[[ 1.        +0.j          0.99940636+0.00171037j  0.99881271+0.00342074j
   0.99769334+0.00599548j  0.99830652+0.00600295j  0.99603082+0.00771714j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.49894048-0.86683882j -0.49788095-0.86765223j
  -0.49652828-0.86891329j  0.        +0.j         -0.49662598-0.86896908j
  -0.49642411-0.86848476j]
 [-0.5       +0.8660254j  -0.50150005+0.86531533j -0.50300009+0.86460525j
  -0.50530172+0.86366797j -0.50531589+0.86234376j  0.        +0.j
   0.        +0.j        ]]
INR:
[[ 4.01485094e-01-0.09790061j  4.01485094e-01-0.09790061j
   3.01281678e-01-0.07321407j  1.00316592e-01-0.02443919j
   1.00586931e-01-0.02432029j  3.33846978e-32+0.j        ]
 [-3.06957935e-01-0.28496385j -3.06957935e-01-0.28496385j
  -2.35528952e-01-0.21069807j  2.53416202e-32+0.j
  -1.64263798e-01-0.13633526j -9.30012991e-02-0.06198372j]
 [-8.65739051e-02+0.29682462j -8.65739051e-02+0.29682462j
  -5.79048331e-02+0.19784366j -2.90025515e-02+0.09896813j
  -2.16

In [ ]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
#             FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
#             FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
#             JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
#             JSUBV_vec, JKVL_vec, JKCL_vec \
#              = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [ ]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(4):
    print(n)
    print(XNR_deep_vec[n, :,0] - XNR_deep_nonvec[n, :,0])
    print('')

n = 1
#print(XNR_deep_vec[n, :,0] - XNR_deep_notvec[n, :,0])

In [ ]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(4):
    print(n)
    print(FT_deep_vec[n, :, :] - FT_deep_nonvec[n, :, :])
    print('')

In [ ]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[n, :,:] - JT_deep_nonvec[n, :,:])

In [ ]:
print('XNR: \n')
for n in range(4): 
    print(XNR_deep_vec[n, :, :] - XNR_deep_nonvec[n, :, :])
    print("\n ")

Split up FT and JT into SUBV, KVL and KCL

In [ ]:
print('ftsubv: \n')
print(FTSUBV_vec.shape)
for n in range(4): 
    print(FTSUBV_vec[n,:,:] - FTSUBV_nonvec[n, :, :])
    print("\n ")
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

In [ ]:
print('ftkvl: \n')
print(FTKVL_vec.shape)
for n in range(4): 
    print(FTKVL_vec[n, :, 0] - FTKVL_nonvec[n, :, 0])
    print("\n ")

In [ ]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(4): 
    print(FTKCL_vec[n, :, :] - FTKCL_nonvec[n, :, :])
    print("\n ")

In [ ]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(4): 
    print(n)
    print("\n")
    print(JSUBV_vec[n, :, :] - JSUBV_nonvec[n, :, :])


In [ ]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(4): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])
    print("\n ")


In [ ]:
print('JKCL: \n')
print(JKCL_vec.shape)
for n in range(4): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])
    print("\n ")
