In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
            FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
            FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
            JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
            JSUBV_vec, JKVL_vec, JKCL_vec \
             = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

ValueError: could not broadcast input array from shape (78,1) into shape (78)

In [ ]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(XNR_deep_vec.shape[2]):
    print(n)
    print(XNR_deep_vec[:,0,n] - XNR_deep_nonvec[:,0,n])
    print('')

n = 0
print(XNR_deep_vec[:,0,n] - XNR_deep_nonvec[:,0,n])

In [4]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(len(FT_deep_vec[0][0])):
    print(n)
    print(FT_deep_vec[:, 0][:, n] - FT_deep_nonvec[:, 0][:, n])
    print('')

    


NameError: name 'FT_deep_nonvec' is not defined

In [5]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[:,:,n] - JT_deep_nonvec[:,:,n])

NameError: name 'JT_deep_nonvec' is not defined

In [6]:
print('XNR: \n')
for n in range(len(XNR_deep_vec[0][0])): 
    print(XNR_deep_vec[:, 0][:, n] - XNR_deep_nonvec[:, 0][:, n])

XNR: 



NameError: name 'XNR_deep_vec' is not defined

Split up FT and JT into SUBV, KVL and KCL; this is off. 

In [8]:
print('ftsubv: \n')
for n in range(len(FTSUBV_vec[0][0])): 
    print(FTSUBV_vec[:,:,n] - FTSUBV_nonvec[:, :, n])
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

ftsubv: 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[ 0.00030966]
 [ 0.00020308]
 [ 0.00018262]
 [-0.00035074]
 [-0.00031258]
 [ 0.00017289]]
[[ 6.54758001e+33]
 [ 1.84393645e+24]
 [ 4.29618018e+23]
 [-3.41031069e+24]
 [ 1.29426296e+25]
 [-2.05825341e+25]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [9]:
print('ftkvl: \n')
#print(FTKVL_vec.shape)
for n in range(len(FTKVL_vec[0][0])): 
    print(FTKVL_vec[:, 0, n] - FTKVL_nonvec[:, 0, n])

ftkvl: 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-2.94909129e-04 -1.99134184e-04  3.52859497e-05 -4.14609909e-04
 -2.82287598e-04  4.48226929e-05  4.04357910e-04 -1.37329102e-03
 -2.22444534e-04 -2.27338076e-03 -1.18227890e-07  1.18227890e-07
 -1.30653381e-04  1.92642212e-04 -4.23431396e-04  3.49521637e-04
  6.10351563e-05 -1.49250031e-03 -3.93384652e-04 -1.84420541e-04
  5.60283661e-06  4.55796719e-04  5.91278076e-05 -6.99043274e-04
  4.01483112e-04  1.90014465e-04 -3.55720520e-04 -3.56197357e-04
 -9.68933105e-04 -4.24385071e-05  1.94549561e-03 -1.14440918e-05
  1.27609675e-17  2.48412225e-16  0.00000000e+00  0.00000000e+00]
[-6.54758001e+33 -1.84393589e+24 -6.54740643e+33  1.29455527e+21
 -6.54772064e+33 -5.43328866e+21 -1.49288711e+31  4.78714259e+22
 -6.56784655e+33  2.77097523e+26 -1.85550945e+23 -2.19328906e+23
 -4.29617941e+23  3.41036973e+24 -8.08283685e+22 -1.05053424e+25
  2.03770655e+26 -5.57674743e+25 -

In [10]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(len(FTKCL_vec[0][0])): 
    print(FTKCL_vec[:, 0, n] - FTKCL_nonvec[:, 0, n])

ftkcl: 

(36, 1, 4)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-3.02156935e+21 -3.22008045e-17 -2.45461240e+21 -2.53135590e-02
 -5.27769627e+21 -2.55441101e-02  5.24380507e+20 -2.55597983e-02
  2.76481643e+17 -2.56759654e-02  0.00000000e+00  0.00000000e+00
 -4.94517601e+18  0.00000000e+00  1.38613206e+22 -2.52728496e-02
 -7.64203843e+22 -2.54626914e-02  0.00000000e+00  0.00000000e+00
 -3.51382422e+21 -2.54588482e-02 -5.52166442e+17 -5.04478947e-02
 -1.13745178e+19  1.38777878e-17  1.94568232e+20 -2.53380706e-02
 -1.73200247e+22 -2.55931334e-02 -9.97563134e+08 -2.56327838e-02
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
[-2.46988788e+56 -6.07153217e-18 -6.06485753e+56 -2.50000035e-02
  7.55812085e+53 -2.50000103e-02  3.18655880e+54 -2.50000131e-02
 -1.10551929e+57 -2.50000104e-02  0.00000000e+00  0.00000000e+00
  2.41128560e+49  5.55111512e-17 -1.79994129e+39 -2.50000013e-02
 -2.04129230e+55 -2.500

In [11]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(len(JSUBV_vec[0][0])): 
    print(n)
    print("\n")
    print(JSUBV_vec[:, :, n] - JSUBV_nonvec[:, :, n])


jsubv: 

(6, 78, 4)
0


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0.

In [12]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(len(JKVL_vec[0][0])): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])


(36, 78, 4)
jkvl: 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 

In [13]:


print('jkcl: \n')
print(JKCL_vec.shape)
for n in range(len(JKCL_vec[0][0])): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])


jkcl: 

(36, 78, 4)
[[ 0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.        -1.         0.         1.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.        

In [14]:
print(XNR_deep_nonvec[:,:,1]) 

[[ 1.00000000e+00]
 [-5.37788578e-19]
 [ 9.99414376e-01]
 [ 1.71420098e-03]
 [ 9.98828751e-01]
 [ 3.42840196e-03]
 [ 9.97722607e-01]
 [ 6.01044974e-03]
 [ 9.98336109e-01]
 [ 6.01395545e-03]
 [ 9.96068064e-01]
 [ 7.74263767e-03]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.00000000e-01]
 [-8.66025404e-01]
 [-4.98945021e-01]
 [-8.66838350e-01]
 [-4.97890041e-01]
 [-8.67651297e-01]
 [-4.96545599e-01]
 [-8.68910395e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.96645279e-01]
 [-8.68959849e-01]
 [-4.96441244e-01]
 [-8.68476242e-01]
 [-5.00000000e-01]
 [ 8.66025404e-01]
 [-5.01506034e-01]
 [ 8.65327558e-01]
 [-5.03012068e-01]
 [ 8.64629712e-01]
 [-5.05323725e-01]
 [ 8.63713580e-01]
 [-5.05345531e-01]
 [ 8.62391172e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 4.00000000e-01]
 [-1.00000000e-01]
 [ 4.00000000e-01]
 [-1.00000000e-01]
 [ 3.00000000e-01]
 [-7.50000000e-02]
 [ 1.00000000e-01]
 [-2.50000000e-02]
 [ 1.00000000e-01]
 [-2.50000000e-02]
 [ 3.1084733

In [ ]:
XNR_deep_nonvec