In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function


In [3]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [4]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec = \
    NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [11]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(XNR_deep_vec.shape[2]):
    print(n)
    print(XNR_deep_vec[:,0,n] - XNR_deep_nonvec[:,0,n])
    print('')

n = 0
print(XNR_deep_vec[:,0,n] - XNR_deep_nonvec[:,0,n])

(78, 1, 4)
(78, 1, 4)
ft: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

2
[-0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446 -0.00046446
 -0.00046446 -0.00046446 -0.00046446 -0.00046446

In [12]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(len(FT_deep_vec[0][0])):
    print(n)
    print(FT_deep_vec[:, 0][:, n] - FT_deep_nonvec[:, 0][:, n])
    print('')

    


(78, 1, 4)
(78, 1, 4)
ft: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

2
[-4.64455710e-04  1.43798839e-04 -4.81395613e-05 -2.00452243e-04
 -2.35648316e-04 -2.37308912e-05  4.98278513e-04 -2.31948842e-04
  5.53131104e-04 -1.56402588e-04  2.01702118e-04  1.24740601e-03
  1.59454346e-03 -1.68228149e-03 -2.63541937e-04 -3.27202491e-04
  4.05531999e-08 -4.05532002e-08  2.44140625e-04  2.26974487e-04
 -6.06536865e-04  6.48498535e-05 -7.97271729e-04 -3.12805176e-04
 -2.00466991e-04 -6.28994911e-05  9.82745551e-04  4.57297079e-04
 -2.67028809e-04  6.21795654e-0

In [21]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[:,:,n] - JT_deep_nonvec[:,:,n])

(78, 78, 4)
(78, 78, 4)
jt: 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.

In [4]:
print('xnr: \n')
for n in range(len(XNR_deep_vec[0][0])): 
    print(XNR_deep_vec[:, 0][:, n] - XNR_deep_notvec[:, 0][:, n])

xnr: 



NameError: name 'XNR_deep_vec' is not defined

In [5]:
print('ftsubv: \n')
for n in range(len(FTSUBV_vec[0][0])): 
    print(FTSUBV_vec[:, 0][:, n] - FTSUBV_nonvec[:, 0][:, n])

ftsubv: 



NameError: name 'FTSUBV_vec' is not defined

In [9]:
print('ftkvl: \n')
for n in range(len(FTKVL_vec[0][0])): 
    print(FTKVL_vec[:, 0][:, n] - FTKVL_nonvec[:, 0][:, n])

ftkvl: 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 4.98278513e-04 -2.31948842e-04  5.53131104e-04 -1.56402588e-04
  2.01702118e-04  1.24740601e-03  1.59454346e-03 -1.68228149e-03
 -2.63541937e-04 -3.27202491e-04  4.05531999e-08 -4.05532002e-08
  2.44140625e-04  2.26974487e-04 -6.06536865e-04  6.48498535e-05
 -7.97271729e-04 -3.12805176e-04 -2.00466991e-04 -6.28994911e-05
  9.82745551e-04  4.57297079e-04 -2.67028809e-04  6.21795654e-04
  9.81376945e-05 -4.52326243e-05 -5.66482544e-04  6.10351562e-04
  3.33786011e-04 -7.66754150e-04 -9.53674316e-06  4.42028046e-04
  3.40567061e-17  2.87508926e-16 -5.78593269e-18 -1.63146656e-18]
[-4.15004123e+33  3.48698286e+22  8.58258528e+33 -7.47094846e+21
 -3.55758654e+32 -2.40097532e+21 -5.77502524e+31  9.15431845e+24
  1.87693927e+32  9.70722100e+22  4.81658127e+23  4.81792090e+23
 -6.69007156e+22 -2.39565129e+22 -1.69376835e+24 -1.90912700e+23
  4.40652682e+24 -1.33523860e+24  

In [10]:
print('ftkcl: \n')
for n in range(len(FTKCL_vec[0][0])): 
    print(FTKCL_vec[:, 0][:, n] - FTKCL_nonvec[:, 0][:, n])

ftkcl: 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-1.60432207e+23 -3.22008045e-17 -1.54976339e+23 -2.53135590e-02
  7.67934272e+22 -2.55441101e-02 -5.33654874e+19 -2.55597983e-02
  1.01983591e+18 -2.56759654e-02 -8.11064071e-08  0.00000000e+00
 -2.94967647e+18  0.00000000e+00  1.30915330e+22 -2.52728496e-02
  5.99108176e+20 -2.54626914e-02 -5.99038022e-04  0.00000000e+00
 -1.95226552e+18 -2.54588482e-02 -1.76170691e+17 -5.04478947e-02
  5.93898719e+20  1.38777878e-17 -8.02877561e+21 -2.53380706e-02
 -2.58882685e+22 -2.55931334e-02 -9.73233106e+08 -2.56327838e-02
  3.16823720e-04  0.00000000e+00  3.16823720e-04  0.00000000e+00]
[ 2.43907694e+59 -6.07153217e-18 -2.72295206e+57 -2.50000035e-02
  4.23472940e+56 -2.50000103e-02 -7.57384388e+56 -2.50000131e-02
 -1.62100048e+52 -2.50000104e-02  3.26971975e+33 -5.57343117e-20
  2.70117947e+42  5.55111512e-17 -4.37833215e+49 -2.50000013e-02
  1.69569260e+51 -2.50000034e-02  

In [11]:
print('jsubv: \n')
for n in range(len(JSUBV_vec[0][0])): 
    print(JSUBV_vec[:, 0][:, n] - JSUBV_nonvec[:, 0][:, n])


jsubv: 

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]


In [12]:

print('jkvl: \n')
for n in range(len(JKVL_vec[0][0])): 
    print(JKVL_vec[:, 0][:, n] - JKVL_nonvec[:, 0][:, n])


jkvl: 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Split up FT and JT into SUBV, KVL and KCL

In [13]:


print('jkcl: \n')
for n in range(len(JKCL_vec[0][0])): 
    print(JKCL_vec[:, 0][:, n] - JKCL_nonvec[:, 0][:, n])


jkcl: 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
