In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function
from lib.network_mapper_OpenDSSnonvec import network_mapper_function as nmf2

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

#------------------


nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 0.85*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.10*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.05*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
network1 = nmf2(fn)
# VNR, iNR, sNR, STXNR, SRXNR, INR, ic = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
BASE
Vbase: 1600.0
Sbase: 577350.2691896257
Ibase: 360.8439182435161
Zbase: 4.434050067376326

NODES
nnode: 7
nodelist: ['sourcebus', 'a01', 'a02', 'a03', 'a04', 'a05', 'a06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]
{'sourcebus': 0, 'a01': 1, 'a02': 2, 'a03': 3, 'a04': 4, 'a05': 5, 'a06': 6}
[1, 1, 1]
[1, 1, 1]
[1, 1, 1]
[1, 0, 1]
[1, 1, 0]
[0, 1, 0]
LINES
nline: 6
TXnode: ['sourcebus', 'a01', 'a02', 'a03', 'a03', 'a05']
RXnode: ['a01', 'a02', 'a03', 'a04', 'a05', 'a06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:

In [4]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
        FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
        FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
        JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
        JSUBV_vec, JKVL_vec, JKCL_vec = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

0
1
2
3
VNR
[[ 1.        +0.j          0.99896295+0.00295913j  0.99792591+0.00591826j
   0.9959725 +0.01037122j  0.99703434+0.01038933j  0.99308369+0.01334137j
   0.        +0.j        ]
 [-0.5       -0.8660254j  -0.49815716-0.86743021j -0.49631432-0.86883502j
  -0.49395785-0.87101365j  0.        +0.j         -0.49412299-0.87111416j
  -0.49377604-0.87027425j]
 [-0.5       +0.8660254j  -0.50258959+0.86478498j -0.50517918+0.86354456j
  -0.50915132+0.86190304j -0.50916576+0.85960883j  0.        +0.j
   0.        +0.j        ]]
INR:
[[ 6.96451536e-01-0.16669287j  6.96451536e-01-0.16669287j
   5.22742372e-01-0.12435854j  1.74002022e-01-0.04157905j
   1.74608451e-01-0.04116811j  2.87317327e-31+0.j        ]
 [-5.30175199e-01-0.49506777j -5.30175199e-01-0.49506777j
  -4.06715514e-01-0.36620383j  4.95424907e-32+0.j
  -2.83721395e-01-0.23702072j -1.60729651e-01-0.10786439j]
 [-1.51890121e-01+0.5135394j  -1.51890121e-01+0.5135394j
  -1.01822041e-01+0.34222745j -5.10470594e-02+0.17120148j
  -1.530

In [ ]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
VNR, iNR, sNR, STXNR, SRXNR, INR,itercount = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [5]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(4):
    print(n)
    print(XNR_deep_vec[n, :,0] - XNR_deep_nonvec[n, :,0])
    print('')

n = 1
#print(XNR_deep_vec[n, :,0] - XNR_deep_notvec[n, :,0])

(101, 78, 1)
(101, 78, 1)
XNR: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[ 0.00000000e+00 -5.56337829e-19 -1.01181989e-03  2.96748614e-03
 -2.02363979e-03  5.93497228e-03 -3.93519512e-03  1.04051139e-02
 -2.87348874e-03  1.04113530e-02 -6.79692556e-03  1.34036556e-02
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.82724846e-03 -1.40191831e-03  3.65449691e-03 -2.80383661e-03
  5.98377905e-03 -4.97430522e-03  0.00000000e+00  0.00000000e+00
  5.81282180e-03 -5.05579456e-03  6.16590068e-03 -4.21892062e-03
  0.00000000e+00  0.00000000e+00 -2.60472425e-03 -1.20247338e-03
 -5.20944850e-03 -2.40494676e-03 -9.20735247e-03 -3.98140767e-03
 -9.24465121e-03 -6.26777971e-03  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -8.12995681e-04  2.03248920e-04
 -8.1299

In [ ]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(4):
    print(n)
    print(FT_deep_vec[n, :, :] - FT_deep_nonvec[n, :, :])
    print('')

In [ ]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[n, :,:] - JT_deep_nonvec[n, :,:])

In [ ]:
print('XNR: \n')
for n in range(4): 
    print(XNR_deep_vec[n, :, :] - XNR_deep_nonvec[n, :, :])
    print("\n ")

Split up FT and JT into SUBV, KVL and KCL

In [ ]:
print('ftsubv: \n')
print(FTSUBV_vec.shape)
for n in range(4): 
    print(FTSUBV_vec[n,:,:] - FTSUBV_nonvec[n, :, :])
    print("\n ")
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

In [ ]:
print('ftkvl: \n')
print(FTKVL_vec.shape)
for n in range(4): 
    print(FTKVL_vec[n, :, 0] - FTKVL_nonvec[n, :, 0])
    print("\n ")

In [ ]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(4): 
    print(FTKCL_vec[n, :, :] - FTKCL_nonvec[n, :, :])
    print("\n ")

In [ ]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(4): 
    print(n)
    print("\n")
    print(JSUBV_vec[n, :, :] - JSUBV_nonvec[n, :, :])


In [ ]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(4): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])
    print("\n ")


In [ ]:
print('JKCL: \n')
print(JKCL_vec.shape)
for n in range(4): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])
    print("\n ")
