In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 0.85*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0.1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.05*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_notvec, \
        FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
        FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
        JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
        JSUBV_vec, JKVL_vec, JKCL_vec = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

0
1
2
3
[[ 1.00000000e+00]
 [ 2.01599394e-26]
 [ 9.99406648e-01]
 [ 1.71074288e-03]
 [ 9.98813296e-01]
 [ 3.42148576e-03]
 [ 9.97694396e-01]
 [ 5.99686944e-03]
 [ 9.98307626e-01]
 [ 6.00437337e-03]
 [ 9.96032048e-01]
 [ 7.71889749e-03]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-5.00000000e-01]
 [-8.66025404e-01]
 [-4.98940050e-01]
 [-8.66837803e-01]
 [-4.97880100e-01]
 [-8.67650201e-01]
 [-4.96526736e-01]
 [-8.68909504e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.96624101e-01]
 [-8.68964386e-01]
 [-4.96422214e-01]
 [-8.68480031e-01]
 [-5.00000000e-01]
 [ 8.66025404e-01]
 [-5.01499854e-01]
 [ 8.65316421e-01]
 [-5.02999708e-01]
 [ 8.64607439e-01]
 [-5.05301008e-01]
 [ 8.63672070e-01]
 [-5.05315091e-01]
 [ 8.62348209e-01]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 4.01309015e-01]
 [-9.78572299e-02]
 [ 4.01309015e-01]
 [-9.78572299e-02]
 [ 3.01128769e-01]
 [-7.31764773e-02]
 [ 1.00284563e-01]
 [-2.44312383e-02]
 [ 1.00510399e-01]
 [-2.43015973e-02]
 [ 1

In [4]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# VNR, iNR, sNR, STXNR, SRXNR, INR = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [5]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
#             FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
#             FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
#             JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
#             JSUBV_vec, JKVL_vec, JKCL_vec \
#              = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [6]:
# fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
# VNR, iNR, sNR, STXNR, SRXNR, INR = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

In [4]:
print(XNR_deep_notvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(4):
    print(n)
    print(XNR_deep_vec[n, :,0] - XNR_deep_notvec[n, :,0])
    print('')

n = 1
print(XNR_deep_vec[n, :,0] - XNR_deep_notvec[n, :,0])

(101, 78, 1)
(101, 78, 1)
XNR: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[ 0.00000000e+00  6.79779097e-18  7.54601841e-05 -9.38124135e-05
  1.50920368e-04 -1.87624827e-04  2.66803608e-04 -3.30644285e-04
  2.63398155e-04 -3.27721271e-04  3.51190090e-04 -4.31801644e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
 -1.44260617e-05  1.55710938e-05 -2.88521234e-05  3.11421876e-05
 -4.72171717e-05  5.47932626e-05  0.00000000e+00  0.00000000e+00
 -4.92297935e-05  3.71881549e-05 -6.07229713e-05  9.89845414e-06
  0.00000000e+00  0.00000000e+00  9.08253909e-05 -1.79907752e-05
  1.81650782e-04 -3.59815503e-05  3.17381016e-04 -6.77932850e-05
  3.25002925e-04 -2.46183762e-05  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -1.47042312e-02  3.73405724e-03
 -1.4704

In [5]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(4):
    print(n)
    print(FT_deep_vec[n, :, :] - FT_deep_nonvec[n, :, :])
    print('')

(101, 78, 1)
(101, 78, 1)
ft: 

0
[[0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.00375   ]
 [0.0009375 ]
 [0.00375   ]
 [0.0009375 ]
 [0.00375   ]
 [0.0009375 ]
 [0.00375   ]
 [0.0009375 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.005625  ]
 [0.00140625]
 [0.005625  ]
 [0.00140625]
 [0.        ]
 [0.        ]
 [0.005625  ]
 [0.00140625]
 [0.005625  ]
 [0.0028125 ]
 [0.        ]
 [0.        ]
 [0.001875  ]


In [6]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[n, :,:] - JT_deep_nonvec[n, :,:])

(101, 78, 78)
(101, 78, 78)
jt: 

[[ 0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.
   0.          0.          0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.          0.          0.    

In [ ]:
print('XNR: \n')
for n in range(4): 
    print(XNR_deep_vec[n, :, :] - XNR_deep_nonvec[n, :, :])
    print("\n ")

Split up FT and JT into SUBV, KVL and KCL

In [7]:
print('ftsubv: \n')
print(FTSUBV_vec.shape)
for n in range(4): 
    print(FTSUBV_vec[n,:,:] - FTSUBV_nonvec[n, :, :])
    print("\n ")
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

ftsubv: 

(101, 6, 1)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

 
[[0.00000000e+00]
 [6.79917248e-18]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]

 
[[ 0.00000000e+00]
 [-7.75327747e-21]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]

 
[[0.00000000e+00]
 [3.08799425e-23]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]

 


In [8]:
print('ftkvl: \n')
print(FTKVL_vec.shape)
for n in range(4): 
    print(FTKVL_vec[n, :, 0] - FTKVL_nonvec[n, :, 0])
    print("\n ")

ftkvl: 

(101, 36, 1)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

 
[ 1.04517089e-16 -7.10873035e-18 -8.02309608e-18 -6.77626358e-18
  1.83013327e-16 -9.75781955e-18 -7.19910243e-17 -4.33680869e-19
 -1.36609474e-17 -2.81892565e-18  2.38740477e-16 -1.45044908e-16
  5.42101086e-17 -3.11708125e-17 -5.78963960e-17  7.83336070e-17
  6.07153217e-17  5.91974386e-17 -1.07520975e-16 -3.13930560e-17
  1.45825192e-17  6.71121145e-17 -5.36680075e-18 -1.37774991e-16
  1.33302657e-16 -1.33424630e-16  2.11961525e-17 -2.32561366e-17
 -1.33682128e-16  2.88939879e-17  1.80411242e-16 -1.79896245e-16
 -6.64204802e-17  2.85302938e-16  0.00000000e+00  0.00000000e+00]

 
[-2.06865775e-16  1.53676266e-19  1.25767452e-16 -2.16840434e-19
 -2.58473798e-16  1.51788304e-18 -7.67615138e-17 -1.78893358e-18
  6.91720986e-17 -6.50521303e-19 -7.91706236e-19  1.67511783e-19
 -7.84962373e-17  9.51929507e-17  3.20923843e-17 -1.59377719e-17
  3.46944695e-1

In [9]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(4): 
    print(FTKCL_vec[n, :, :] - FTKCL_nonvec[n, :, :])
    print("\n ")

ftkcl: 

(101, 36, 1)
[[0.        ]
 [0.        ]
 [0.00375   ]
 [0.0009375 ]
 [0.00375   ]
 [0.0009375 ]
 [0.00375   ]
 [0.0009375 ]
 [0.00375   ]
 [0.0009375 ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.005625  ]
 [0.00140625]
 [0.005625  ]
 [0.00140625]
 [0.        ]
 [0.        ]
 [0.005625  ]
 [0.00140625]
 [0.005625  ]
 [0.0028125 ]
 [0.        ]
 [0.        ]
 [0.001875  ]
 [0.00046875]
 [0.001875  ]
 [0.00046875]
 [0.001875  ]
 [0.00046875]
 [0.        ]
 [0.        ]
 [0.        ]
 [0.        ]]

 
[[-1.16090948e-16]
 [ 7.17741838e-17]
 [ 2.66840127e-05]
 [-3.46064235e-05]
 [ 4.79022471e-05]
 [-6.03380663e-05]
 [ 4.52696930e-05]
 [-6.08162049e-05]
 [ 6.61949972e-05]
 [-7.68244962e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-1.38777878e-16]
 [ 2.49800181e-16]
 [ 1.53344426e-06]
 [-1.80124182e-05]
 [ 1.34186089e-06]
 [-3.05008472e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 2.10096890e-06]
 [-2.91973262e-05]
 [ 1.50497540e-05]
 [-2.51459932e-05]
 [ 5.55111512e

In [10]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(4): 
    print(n)
    print("\n")
    print(JSUBV_vec[n, :, :] - JSUBV_nonvec[n, :, :])


jsubv: 

(101, 6, 78)
0


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [

In [11]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(4): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])
    print("\n ")


(101, 36, 78)
jkvl: 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.


In [12]:
print('JKCL: \n')
print(JKCL_vec.shape)
for n in range(4): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])
    print("\n ")


JKCL: 

(101, 36, 78)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
