In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = 1*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
            FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
            FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
            JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
            JSUBV_vec, JKVL_vec, JKCL_vec \
             = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

START 
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[2. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[2. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 5. 0. 0.]]]
[[[2. 0. 0. 0.]
  [0. 0. 0. 7.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 5. 0. 0.]]]
[[[2. 0. 0. 0.]
  [0. 0. 0. 8.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 5. 0. 0.]]]
[[[1. 0. 0. 0.]
  [1. 0. 0. 8.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 5. 0. 0.]]]
(36, 78)
(1, 78)
xnr1
[[ 1.00030966e+00]
 [ 2.03077959e-04]
 [ 2.51100938e+08]
 [ 1.28262950e+09]
 [-2.18486694e+08]
 [-1.17105730e+09]
 [ 3.94628982e+10]
 [ 9.01948727e+09]
 [ 3.94242182e+10]
 [ 8.82608698e+09]
 [ 4.10645005e+10]
 [ 9.24092054e+09]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-4.

In [4]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(4):
    print(n)
    print(XNR_deep_vec[n, :,0] - XNR_deep_nonvec[n, :,0])
    print('')

n = 1
print(XNR_deep_vec[n, :,0] - XNR_deep_nonvec[n, :,0])

(4, 78, 1)
(4, 78, 1)
XNR: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[ 3.09660782e-04  2.03077959e-04  2.51100937e+08  1.28262950e+09
 -2.18486695e+08 -1.17105730e+09  3.94628982e+10  9.01948727e+09
  3.94242182e+10  8.82608698e+09  4.10645005e+10  9.24092054e+09
  0.00000000e+00  0.00000000e+00  1.82620938e-04 -3.50735862e-04
 -1.78978283e+09  2.30820288e+09  1.83009826e+09 -2.19024227e+09
  1.36400380e+10 -7.22512481e+09  0.00000000e+00  0.00000000e+00
  1.41833203e+10 -7.70263236e+09  1.41834056e+10 -7.70270735e+09
 -3.12580532e-04  1.72892389e-04 -1.79393977e+09  2.30085458e+09
  1.83114938e+09 -2.28400012e+09  3.89378336e+10  6.55449628e+09
  3.92085941e+10  6.20637576e+09  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -3.92698848e+11 -3.92698848e+11
  7.85181964

In [5]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(4):
    print(n)
    print(FT_deep_vec[n, :, :] - FT_deep_nonvec[n, :, :])
    print('')

    


(4, 78, 1)
(4, 78, 1)
ft: 

0
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

1
[[ 3.09660782e-04]
 [ 2.03077959e-04]
 [ 1.82620938e-04]
 [-3.50735862e-04]
 [-3.12580532e-04]
 [ 1.72892389e-04]
 [-2.94909129e-04]
 [-1.99134184e-04]
 [ 3.52859497e-05]
 [-4.14609909e-04]
 [-2.82287598e-04]
 [ 4.48226929e-05]
 [ 4.04357910e-04]
 [-1.37329102e-03]
 [-2.22444534e-04]
 [-2.27338076e-03]
 [-1.18227890e-07]
 [ 1.18227890e-07]
 [-1.30653381e-04]
 [ 1.92642212e-04]
 [-4.23431396e-04]
 [ 3.49521637e-04]
 [ 6.10351563e-05]
 [-1.49250031e-03]
 [-3.93384652e-04]
 [-1.84420541e-04]
 [ 5

In [6]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[n, :,:] - JT_deep_nonvec[n, :,:])

(4, 78, 78)
(4, 78, 78)
jt: 

[[ 0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.       ]
 [ 0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         0.         0.
   0.         0.         0.         0.         

In [7]:
print('XNR: \n')
for n in range(4): 
    print(XNR_deep_vec[n, :, :] - XNR_deep_nonvec[n, :, :])

XNR: 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[ 3.09660782e-04]
 [ 2.03077959e-04]
 [ 2.51100937e+08]
 [ 1.28262950e+09]
 [-2.18486695e+08]
 [-1.17105730e+09]
 [ 3.94628982e+10]
 [ 9.01948727e+09]
 [ 3.94242182e+10]
 [ 8.82608698e+09]
 [ 4.10645005e+10]
 [ 9.24092054e+09]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 1.82620938e-04]
 [-3.50735862e-04]
 [-1.78978283e+09]
 [ 2.30820288e+09]
 [ 1.83009826e+09]
 [-2.19024227e+09]
 [ 1.36400380e+10]
 [-7.22512481e+09]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 1.41833203e+10]
 [-7.70263236e+09]
 [ 1.41834056e+10]
 [-7.702707

Split up FT and JT into SUBV, KVL and KCL

In [ ]:
print('ftsubv: \n')
for n in range(len(FTSUBV_vec[0][0])): 
    print(FTSUBV_vec[:,:,n] - FTSUBV_nonvec[:, :, n])
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

In [ ]:
print('ftkvl: \n')
#print(FTKVL_vec.shape)
for n in range(len(FTKVL_vec[0][0])): 
    print(FTKVL_vec[:, 0, n] - FTKVL_nonvec[:, 0, n])

In [ ]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(len(FTKCL_vec[0][0])): 
    print(FTKCL_vec[:, 0, n] - FTKCL_nonvec[:, 0, n])

In [ ]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(len(JSUBV_vec[0][0])): 
    print(n)
    print("\n")
    print(JSUBV_vec[:, :, n] - JSUBV_nonvec[:, :, n])


In [ ]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(len(JKVL_vec[0][0])): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])


In [ ]:


print('jkcl: \n')
print(JKCL_vec.shape)
for n in range(len(JKCL_vec[0][0])): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])


In [ ]:
print(XNR_deep_nonvec[:,:,1]) 

In [ ]:
XNR_deep_nonvec