In [1]:
import numpy as np
import opendssdirect as dss
import matplotlib.pyplot as plt
import copy
import pandas as pd
import time
import re
import sys
from lib.network_mapper import network_mapper_function
from lib.compute_simultaneously import NR3_function

In [2]:
fp = "C:\\Users\\kathl\\Desktop\\LinDist3Flow\\20180601\\PYTHON\\"
#fp = '/home/michael/Desktop/git/LinDist3Flow/20180601/PYTHON/'
fn = 'compare_lindist3flow_05node_threephase_unbalanced_oscillation_03.txt'
network1 = network_mapper_function(fp, fn)

nnode1 = network1.nodes.nnode
nline1 = network1.lines.nline

# Network paramaters

nnode = network1.nodes.nnode
nline = network1.lines.nline

# Load parameters

network1.loads.aPQ = .9*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aI = 0*np.ones((3,nnode1))*(network1.loads.spu != 0)
network1.loads.aZ = 0.1*np.ones((3,nnode1))*(network1.loads.spu != 0)


#network1.loads.spu = 1.25*network1.loads.spu
network1.cons.wpu = np.zeros((3,nnode))
network1.vvc.vvcpu = np.zeros((3,nnode))

slackidx = 0
Vslack = np.array([1, np.exp(1j*-120*np.pi/180), np.exp(1j*120*np.pi/180)])



BASE
Vbase: 2771.2812921102036
Sbase: 1000000.0
Ibase: 360.8439182435161
Zbase: 7.68

NODES
nnode: 7
nodelist: ['sub', 'A01', 'A02', 'A03', 'A04', 'A05', 'A06']
phases: ['abc', 'abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 1 0]
 [1 1 1 1 0 1 1]
 [1 1 1 1 1 0 0]]

LINES
nline: 6
TXnode: ['sub', 'A01', 'A02', 'A03', 'A03', 'A05']
RXnode: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06']
TXnum: [0 1 2 3 3 5]
RXnum: [1 2 3 4 5 6]
phases: ['abc', 'abc', 'abc', 'ac', 'ab', 'b']
PH:
 [[1 1 1 1 1 0]
 [1 1 1 0 1 1]
 [1 1 1 1 0 0]]
config: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
length: [1. 1. 1. 1. 1. 1.]

NODES + LINES
inlines:
 [[-1  0  1  2  3  4  5]]
innodes:
 [[-1  0  1  2  3  3  5]]
outlines:
 [[ 0  1  2  3 -1  5 -1]
 [-1 -1 -1  4 -1 -1 -1]]
outnodes:
 [[ 1  2  3  4 -1  6 -1]
 [-1 -1 -1  5 -1 -1 -1]]

CONFIGS
nconf: 6
conflist: ['sub_a01', 'a01_a02', 'a02_a03', 'a03_a04', 'a03_a05', 'a05_a06']
sub_a01 - FZpl:
 [[0.00195312+0.00130208j 0.00065104+0.00520833j 0.

In [3]:
fn = 'compare_opendss_05node_threephase_unbalanced_oscillation_03.dss'
FT_deep_vec, FT_deep_nonvec, JT_deep_vec, JT_deep_nonvec, XNR_deep_vec, XNR_deep_nonvec, \
            FTSUBV_nonvec, FTKVL_nonvec, FTKCL_nonvec, \
            FTSUBV_vec, FTKVL_vec, FTKCL_vec, \
            JSUBV_nonvec, JKVL_nonvec, JKCL_nonvec, \
            JSUBV_vec, JKVL_vec, JKCL_vec \
             = NR3_function(network1, fn, slackidx,Vslack,None,None,None,None)

IT CONVERGED !! 


In [4]:
print(XNR_deep_nonvec.shape)
print(XNR_deep_vec.shape)

print('XNR: \n')
for n in range(4):
    print(n)
    print(XNR_deep_vec[n, :,0] - XNR_deep_nonvec[n, :,0])
    print('')

n = 1
print(XNR_deep_vec[n, :,0] - XNR_deep_nonvec[n, :,0])

(14, 78, 1)
(14, 78, 1)
XNR: 

0
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]

1
[ 0.00000000e+00 -1.01159846e-19 -5.85311656e-05  1.71455846e-04
 -1.17062331e-04  3.42911693e-04 -2.27626548e-04  6.01177249e-04
 -1.66271248e-04  6.01531665e-04 -3.93060159e-04  7.74430427e-04
  0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.05540903e-04 -8.11915754e-05  2.11081806e-04 -1.62383151e-04
  3.45595833e-04 -2.88114740e-04  0.00000000e+00  0.00000000e+00
  3.35661386e-04 -2.92969401e-04  3.56066246e-04 -2.44605433e-04
  0.00000000e+00  0.00000000e+00 -1.50581474e-04 -6.96746703e-05
 -3.01162949e-04 -1.39349341e-04 -5.32291274e-04 -2.30770454e-04
 -5.34462335e-04 -3.62974685e-04  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00  3.99819196e-02 -9.99547990e-03
  3.998191

In [5]:
print(FT_deep_nonvec.shape)
print(FT_deep_vec.shape)

print('ft: \n')
for n in range(4):
    print(n)
    print(FT_deep_vec[n, :, :] - FT_deep_nonvec[n, :, :])
    print('')

    


(14, 78, 1)
(14, 78, 1)
ft: 

0
[[ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.005 ]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]]

1
[[ 0.00000000e+00]
 [-1.01159846e-19]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.000000

In [6]:
print(JT_deep_nonvec.shape)
print(JT_deep_vec.shape)

print('jt: \n')
# for n in range(len(JT_deep_vec[0][0])): 
#     print(JT_deep_vec[:, :, n] - JT_deep_nonvec[:, :, n])

n = 0
print(JT_deep_vec[n, :,:] - JT_deep_nonvec[n, :,:])

(14, 78, 78)
(14, 78, 78)
jt: 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 

In [7]:
print('XNR: \n')
for n in range(4): 
    print(XNR_deep_vec[n, :, :] - XNR_deep_nonvec[n, :, :])

XNR: 

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[ 0.00000000e+00]
 [-1.01159846e-19]
 [-5.85311656e-05]
 [ 1.71455846e-04]
 [-1.17062331e-04]
 [ 3.42911693e-04]
 [-2.27626548e-04]
 [ 6.01177249e-04]
 [-1.66271248e-04]
 [ 6.01531665e-04]
 [-3.93060159e-04]
 [ 7.74430427e-04]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 1.05540903e-04]
 [-8.11915754e-05]
 [ 2.11081806e-04]
 [-1.62383151e-04]
 [ 3.45595833e-04]
 [-2.88114740e-04]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 3.35661386e-04]
 [-2.92969401e-04]
 [ 3.56066246e-04]
 [-2.446054

Split up FT and JT into SUBV, KVL and KCL

In [8]:
print('ftsubv: \n')
print(FTSUBV_vec.shape)
for n in range(4): 
    print(FTSUBV_vec[n,:,:] - FTSUBV_nonvec[n, :, :])
# print(FTSUBV_vec.shape)
# print(FTSUBV_nonvec.shape)

ftsubv: 

(14, 6, 1)
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[ 0.00000000e+00]
 [-1.01159846e-19]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 0.00000000e+00]]
[[0.00000000e+00]
 [8.83713357e-21]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]
[[0.00000000e+00]
 [9.72080968e-23]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]
 [0.00000000e+00]]


In [9]:
print('ftkvl: \n')
print(FTKVL_vec.shape)
for n in range(4): 
    print(FTKVL_vec[n, :, 0] - FTKVL_nonvec[n, :, 0])

ftkvl: 

(14, 36, 1)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[-1.93421668e-16 -1.98446829e-19  2.86229374e-17  7.04731412e-19
 -6.35342473e-17  5.42101086e-19 -5.49690501e-17 -1.62630326e-19
 -3.44776291e-17  2.16840434e-19  1.50981071e-17  2.89686801e-18
 -1.56125113e-17  1.00342911e-16  3.94649591e-17  2.10931533e-16
 -1.38777878e-17 -1.67292395e-16  1.26871589e-17  2.69807186e-18
 -2.84060969e-17 -1.26851654e-17  5.04154010e-18  8.07459568e-17
  5.81132364e-17  1.31798327e-16  1.13624388e-16  1.31066490e-16
 -1.49945160e-16 -5.65140382e-17 -6.66784336e-18 -7.68292764e-17
  1.99766887e-18  6.86598687e-18  0.00000000e+00  0.00000000e+00]
[ 2.32669786e-16  9.14723613e-20 -9.99634403e-17  4.87890978e-19
  2.05347891e-16 -7.58941521e-19  1.81061763e-17  1.40946282e-18
 -5.52943108e-17  1.08420217e-18  8.06678498e-20  7.47895680e-19
 -7.84962373e-17 -1.48264647e-16  8.82540568e-17  7.42678488e-17
  4.33680869e-19  1.20

In [10]:
print('ftkcl: \n')
print(FTKCL_vec.shape)
for n in range(4): 
    print(FTKCL_vec[n, :, :] - FTKCL_nonvec[n, :, :])

ftkcl: 

(14, 36, 1)
[[ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.005 ]
 [ 0.    ]
 [ 0.    ]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [-0.01  ]
 [-0.0025]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]
 [ 0.    ]]
[[ 3.12521276e-17]
 [ 1.51788304e-17]
 [-1.75811999e-05]
 [ 6.48137907e-05]
 [-3.12127233e-05]
 [ 1.13504226e-04]
 [-3.06049459e-05]
 [ 1.13742586e-04]
 [-4.13826593e-05]
 [ 1.45869577e-04]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [ 5.55111512e-17]
 [-5.55111512e-17]
 [-1.22601703e-05]
 [ 5.02324419e-05]
 [-2.04955003e-05]
 [ 8.43915709e-05]
 [ 0.00000000e+00]
 [ 0.00000000e+00]
 [-2.01062405e-05]
 [ 8.32435025e-05]
 [-4.07641202e-05]
 [ 8.19078232e-05]
 [-5.55111512e-17]
 [-2.77555756e-17]
 [-1.55099505e-05]
 [ 6.28440569e-05]
 [-2.70528653e-05]
 [ 1.09605489e-04]
 [-3.1491216

In [11]:
print('jsubv: \n')
print(JSUBV_vec.shape)
for n in range(4): 
    print(n)
    print("\n")
    print(JSUBV_vec[n, :, :] - JSUBV_nonvec[n, :, :])


jsubv: 

(14, 6, 78)
0


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0.]
 [0

In [12]:

print(JKVL_vec.shape)
print('jkvl: \n')
for n in range(4): 
    print(JKVL_vec[:, :, n] - JKVL_nonvec[:, :, n])


(14, 36, 78)
jkvl: 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

In [13]:


print('jkcl: \n')
print(JKCL_vec.shape)
for n in range(4): 
    print(JKCL_vec[:, :, n] - JKCL_nonvec[:, :, n])


jkcl: 

(14, 36, 78)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 

In [15]:
XNR_deep_nonvec

array([[[ 1.00000000e+00],
        [ 0.00000000e+00],
        [ 1.00000000e+00],
        [ 0.00000000e+00],
        [ 1.00000000e+00],
        [ 0.00000000e+00],
        [ 1.00000000e+00],
        [ 0.00000000e+00],
        [ 1.00000000e+00],
        [ 0.00000000e+00],
        [ 1.00000000e+00],
        [ 0.00000000e+00],
        [ 1.00000000e+00],
        [ 0.00000000e+00],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [-8.66025404e-01],
        [-5.00000000e-01],
        [ 8.66025404e-01],
        [-5.00000000e-01],
        [ 8.66025404e-01],
        [-5.00000000e-01],
        [ 8.66025404e-01],
        [-5.00000000e-01],
        [ 8.66025404e-01],
        [-5.00000000e-01],
 

In [16]:
k1 = 0
k2 = 12
print(JKCL_vec.shape)
print(JKCL_nonvec[k1, k2, :])
print(JKCL_vec[k1, k2, :])

(14, 36, 78)
[ 0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
 -0.5       -0.8660254  0.5        0.8660254  0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.       ]
[ 0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.    